---
title: "flat_data_contamination.Rmd"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(here)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# gg_map_data_contamination_rocchmv

```{r function-gg_map_data_contamination_rocchmv}
#' Title
#' 
#' Description
#' 
#' @param data 
#' @param estuary 
#' @param color 
#'
#' @return ggplot
#' 
#' @export
gg_map_data_contamination_rocchmv <- function(data, estuary, color) {
  
  data <- data |>
   count(ESTUARY, YEAR, LIEU_MNEMONIQUE, latitude, longitude)
  
  data_summarized <- data |>
    count(ESTUARY, LIEU_MNEMONIQUE, latitude, longitude)
  
  # Convert to spatial object
  points_sf <- st_as_sf(data_summarized,
                        coords = c("longitude", "latitude"),
                        crs = 4326) |>
    filter(ESTUARY == estuary)
  
  # Define spatial window around points
  bbox <- st_bbox(points_sf)
  marge <- 0.1
  xlim <- c(bbox["xmin"] - marge, bbox["xmax"] + marge)
  ylim <- c(bbox["ymin"] - marge, bbox["ymax"] + marge)
  
  # Plot
  ggplot() +
    geom_sf(data = esteem.overview::fr_map, fill = "grey95", color = "grey50") +
    geom_sf(data = points_sf, size = 1, color = color) +
    geom_text(
      data = data_summarized,
      aes(x = longitude, y = latitude, label = n),
      inherit.aes = FALSE,
      hjust = 0, vjust = 2, size = 4, fontface = "bold"
    ) +
    coord_sf(xlim = xlim, ylim = ylim, expand = FALSE) +
    labs(title = paste0(estuary, " estuary")) +
    theme_minimal()
}
```
  
```{r example-gg_map_data_contamination_rocchmv}
gg_map_data_contamination_rocchmv()
```
  
```{r tests-gg_map_data_contamination_rocchmv}
test_that("gg_map_data_contamination_rocchmv works", {
  expect_true(inherits(gg_map_data_contamination_rocchmv, "function")) 
})
```
  


# spearman_test
 
```{r function-spearman_test}
#' Get results from Spearman's test
#' 
#' Save rho and p.value from Spearman's test in a tibble
#' 
#' @param x first variable
#' @param y second variable
#'
#' @return tibble rho and p.value from Spearman's test
#' 
#' @export
spearman_test <- function(x, y) {
  test <- cor.test(x, y, method = "spearman")
  tibble(rho = test$estimate, p.value = test$p.value)
}
```
  
```{r example-spearman_test}
# spearman_test()
```
  
```{r tests-spearman_test}
test_that("spearman_test works", {
  expect_true(inherits(spearman_test, "function")) 
})
```

# get_last_trend_info

```{r function-get_last_trend_info}
#' Get results from Spearman's test for several estuaries and contaminant
#' 
#' Last 15 years trend and significance
#' 
#' @param data tibble with ESTUARY, PARAMETRE_LIBELLE, YEAR, RESULTAT
#' @param norm tibble PARAMETRE_LIBELLE, NORM
#'
#' @return tibble ESTUARY, PARAMETRE_LIBELLE, rho, p.value, symbol, last_year, last_resultat, norm
#' 
#' @export
get_last_trend_info <- function(data, norm){
  data_last_trend <- data |> 
  filter(last_trend == "Last 15 years")

df_last_info <- data_last_trend |> 
  group_by(ESTUARY, PARAMETRE_LIBELLE) |> 
  summarise(
    last_year = max(YEAR),
    last_resultat = median(RESULTAT[which(YEAR == max(YEAR))]),
    .groups = "drop")

resultats <- data_last_trend  |> 
  group_by(ESTUARY, PARAMETRE_LIBELLE)  |> 
  summarise(
    res = list(spearman_test(x = YEAR, y = RESULTAT)),
    .groups = "drop"
  ) |> 
  unnest(res) |> 
  mutate(symbol = case_when(
    p.value > 0.05 ~ "\u2192",
    rho > 0 ~ "↑",
    rho < 0 ~ "↓",
    TRUE ~ NA
  ))

res_trends <- resultats |> 
  left_join(df_last_info, by = c("ESTUARY", "PARAMETRE_LIBELLE")) |> 
  left_join(norm)
  
return(res_trends)
}
```
  
```{r example-get_last_trend_info}
# get_last_trend_info()
```
  
```{r tests-get_last_trend_info}
test_that("get_last_trend_info works", {
  expect_true(inherits(get_last_trend_info, "function")) 
})
```
  

# get_kruskal_periods_results
    
```{r development-get_kruskal_periods_results}
# You can prepare the code of the get_kruskal_periods_results() function here
```
  
```{r function-get_kruskal_periods_results}
#' Get results of Kruskal-Wallis test between two periods of time
#' 
#' Get all information of Kruskal-Wallis test by PARAMETRE_LIBELLE and ESTUARY to be plotted
#' 
#' @param data_with_periode Dataset with columns ESTUARY, PARAMETRE_LIBELLE, RESULTAT, periode
#' @param chemicals vector of existing values in PARAMETRE_LIBELLE
#' @param estuaries vector of existing values in ESTUARY
#'
#' @return tibble containing, ESTUARY, PARAMETRE_LIBELLE, pvalue, median_1 (first period), median_2 (last period), max_value, trend (symbol to be plotted), y_pos (y position to be plotted)
#' 
#' @export
get_kruskal_periods_results <- function(data_with_periode, chemicals, 
                                         estuaries = c("Gironde", "Loire", "Seine")){
  
  # Create an empty tibble
  res_kruskal_periode <- tibble(ESTUARY = NA, PARAMETRE_LIBELLE = NA, pvalue = NA, 
                                 median_1 = NA, median_2 = NA, max_value = NA)
  
  for(chem in 1:length(chemicals)) {
    for (est in 1:length(estuaries)) {
      name_estuary <- estuaries[est]
      name_chemical <- chemicals[chem]
      # Filter data for a given estuary X chemical
      data_filtered <- data_with_periode |> 
        filter(PARAMETRE_LIBELLE == name_chemical, ESTUARY == name_estuary) |> 
        drop_na(periode)
      # Max value
      max_value = signif(max(data_filtered$RESULTAT), digits = 3)
      # Compute median values for the first and last period
      res_median <- data_filtered |> 
        group_by(periode) |> 
        summarise(median = median(RESULTAT) |> signif(4))
      # Test median difference
      kruskal_pvalue <- signif(kruskal.test(data_filtered$RESULTAT, data_filtered$periode)[["p.value"]], digits = 3)
      # Save results in the tibble
      res_kruskal_periode <- rbind(
        res_kruskal_periode,
        c(name_estuary, name_chemical, kruskal_pvalue, res_median$median, max_value)
      )
    }
  }
  # Get rid of the first line of the tibble created at its initialisation
  res_kruskal_periode <- res_kruskal_periode |> drop_na()
  
  # Mutate median columns to numerical and compute max median
  res_kruskal_periode <- res_kruskal_periode |> 
    mutate(median_1 = as.numeric(median_1),
           median_2 = as.numeric(median_2),
           max_value = as.numeric(max_value))
  
  # Get trend symbol
  res_kruskal_periode <- res_kruskal_periode |>
    mutate(
      trend = case_when(
        pvalue > 0.05 ~ "\u2192",
        median_1 > median_2 ~ "↓",
        median_2 > median_1 ~ "↑",
        TRUE ~ NA
      )
    )
  
  # Get max value by PARAMETRE_LIBELLE
  res_kruskal_periode <- res_kruskal_periode |>
    group_by(PARAMETRE_LIBELLE) |> 
    mutate(y_pos = max(max_value)) |> 
    ungroup()
  
  # Return tibble
  return(res_kruskal_periode)
}
```
  
```{r example-get_kruskal_periods_results}
# get_kruskal_periods_results()
```
  
```{r tests-get_kruskal_periods_results}
test_that("get_kruskal_periods_results works", {
  expect_true(inherits(get_kruskal_periods_results, "function")) 
})
```
  

# get_general_levels
    
```{r development-get_general_levels}
# You can prepare the code of the get_general_levels() function here
```
  
```{r function-get_general_levels}
#' Get general levels in the original unit of measurment
#' 
#' @param data tibble with ESTUARY, PARAMETRE_LIBELLE, periode, RESULTAT
#' @param family character Family folder name
#' @param suffix character If necessary, a suffix for the output .xlsx file name
#'
#' @return save a .xlsx in the folder "../inst/results/data_contam/"
#' 
#' @export
get_general_levels <- function(data, family, suffix){
  
  data_general_levels_estuary <- data |> 
  drop_na(periode) |> 
  group_by(ESTUARY, PARAMETRE_LIBELLE, periode) |> 
  summarise(median_ng_gww = median(RESULTAT), .groups = "drop") |> 
  arrange(PARAMETRE_LIBELLE) |> 
  pivot_wider(names_from = periode, values_from = median_ng_gww)

data_general_levels <- data |> 
  drop_na(periode) |> 
  group_by(PARAMETRE_LIBELLE, periode) |> 
  summarise(median_ng_gww = median(RESULTAT), .groups = "drop") |> 
  arrange(PARAMETRE_LIBELLE) |> 
  pivot_wider(names_from = periode, values_from = median_ng_gww)

writexl::write_xlsx(x = list(data_general_levels, data_general_levels_estuary), path = paste0("../inst/results/data_contam/", family, "/summarised_levels_data_", family, suffix, ".xlsx"))
}
```
  
```{r example-get_general_levels}
# get_general_levels()
```
  
```{r tests-get_general_levels}
test_that("get_general_levels works", {
  expect_true(inherits(get_general_levels, "function")) 
})
```
  


# get_general_evaluation
    
```{r development-get_general_evaluation}
# You can prepare the code of the get_general_evaluation() function here
```
  
```{r function-get_general_evaluation}
#' Title
#' 
#' Description
#' 
#' @param family character Family folder name
#' @param suffix character If necessary, a suffix for the output .xlsx file name
#' @param res_family_trends tibble 
#' @param res_kruskal tibble
#'
#' @return save a .xlsx in the folder "../inst/results/data_contam/"
#' 
#' @export
get_general_evaluation <- function(family, 
                                   suffix = "",
                                   res_family_trends,
                                   res_kruskal) {
  
  # Last trend
  short_last_trend_family <- res_family_trends |>
    rename(short_last_trend = symbol) |>
    select(-last_year, -last_year, -last_resultat)
  
  # Long term evolution
  long_term_family <- res_kruskal |>
    mutate(
      status = case_when(
        median_2 >= 0 & median_2 < 50 ~ "blue",
        median_2 >= 50 & median_2 < 100 ~ "green",
        median_2 >= 100 & median_2 < 150 ~ "yellow",
        median_2 >= 150 & median_2 < 300 ~ "orange",
        median_2 >= 300 & median_2 < 500 ~ "red",
        median_2 >= 500 ~ "black"
      )
    ) |>
    rename(long_term_trend = trend) |>
    select(-max_value, -y_pos)
  
  general_eval_family <- full_join(short_last_trend_family, long_term_family)

  general_eval_family_table <- general_eval_family  |>
    unite(col = eval, long_term_trend, short_last_trend, status, sep = "  ") |>
    select(ESTUARY, PARAMETRE_LIBELLE, eval) |> 
    arrange(ESTUARY) |>
    pivot_wider(names_from = ESTUARY, values_from = eval) 
  
  writexl::write_xlsx(x = list(general_eval_family_table, general_eval_family), 
                    path = paste0("../inst/results/data_contam/", family, "/general_eval_", family, suffix, ".xlsx"))
}
```
  
```{r example-get_general_evaluation}
# get_general_evaluation()
```
  
```{r tests-get_general_evaluation}
test_that("get_general_evaluation works", {
  expect_true(inherits(get_general_evaluation, "function")) 
})
```
  

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_data_contamination.Rmd", vignette_name = NULL, document = FALSE, check = FALSE)
```

