---
title: "flat_utils.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# ggplot2_colors
    
```{r function-ggplot2_colors}
#' ggplot2 colors
#' 
#' Reproduce a vector of colors like those from {ggplot2}
#' 
#' @param n number of colors needed
#'
#' @return vector of hexadecimal colors
#' 
#' @export
ggplot2_colors <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}
```
  
```{r example-ggplot2_colors}
ggplot2_colors(1)
```
  
```{r tests-ggplot2_colors}
test_that("ggplot2_colors works", {
  expect_true(inherits(ggplot2_colors, "function")) 
  expect_equal(object = ggplot2_colors(1),
               expected = c("#F8766D"))
})
```
  
# make_points_sf

  
```{r function-make_points_sf}
#' Make points_sf from "longitude" & "latitude" in a dataset
#' 
#' @noRd
make_points_sf <- function(data) {
  data |>
    dplyr::filter(!is.na(latitude) & !is.na(longitude)) |>
    sf::st_as_sf(
      coords = c("longitude", "latitude"),
      crs = 4326,
      remove = FALSE
    )
}
```


# theme_esteem

```{r function-theme_esteem}
#' Theme global pour le package avec police Windows sûre
#' @importFrom ggplot2 theme_minimal
#'
#' @param base_size 
#' @param base_family 
#'
#' @export
theme_esteem <- function(base_size = 11, base_family = "sans") {
  ggplot2::theme_minimal(base_size = base_size, base_family = base_family)
}
```
  

# get_shortened_path

```{r function-get_shortened_path}
#' Copy an image in a temporary shortened path 
#' Necessary to use knitr::include_graphics for long paths
#' 
#' @return short path to a temp file copy "plot.jpg"
#' 
#' @export
get_shortened_path <- function(complete_path){
  
  img_path <- system.file(complete_path, package = "esteem.overview")
  
  short_path <- tempfile(fileext = ".jpg")
  
  file.copy(img_path, short_path)
  
  return(short_path)
}
```


# get_info_from_dates
    
```{r function-get_info_from_dates}
#' Get information from dates
#' 
#' Get year, month, year_month, season, and year_season variables from a date variable
#' 
#' @param data tibble containing a column of class date
#' @param date_variable name of the date column
#'
#' @return the tibble + variables year, month, year_month, season, and year_season
#' 
#' @import dplyr
#' @importFrom lubridate year month
#' 
#' @export
get_info_from_dates <- function(data, date_variable){
  
    completed_data <- data |> 
      mutate(
        year = lubridate::year({{ date_variable }}),
        month = lubridate::month({{ date_variable }}),
        year_month = paste(year,month, sep = "_"),
        season = lubridate::month({{ date_variable }})
        ) |> 
      mutate(season = case_when(
  month %in% c(12, 1, 2) ~ "winter",
  month %in% c(3,4,5) ~ "spring",
  month %in% c(6,7,8) ~ "summer",
  month %in% c(9,10,11) ~ "autumn"
)) |>
  mutate(year_season = paste(year, season, sep = "_"))
    
    return(completed_data)
}
```

```{r example-get_info_from_dates}
# data("economics")
# get_info_from_dates(data = economics, date_variable = date)
```
  
  
# get_estuary_from_gps_position
    
```{r function-get_estuary_from_gps_position}
#' Get estuary variable from GPS positions
#' 
#' @param data tibble containing columns with GPS position through latitude and longitude columns
#' @param latitude name of latitude column
#' @param longitude name of longitude column
#'
#' @return the tibble + variable estuary
#' 
#' @export

get_estuary_from_gps_position <- function(data, latitude, longitude){
  
  completed_data <- data |>
    
    # ---- Add estuary variable ----
  mutate(
    estuary = case_when(
      {{latitude}} >= GPS_limits_estuary[which(GPS_limits_estuary$estuary == "Gironde"), ]$estuary_limit_lat_min &
        {{latitude}} <= GPS_limits_estuary[which(GPS_limits_estuary$estuary == "Gironde"), ]$estuary_limit_lat_max &
        {{longitude}} >= GPS_limits_estuary[which(GPS_limits_estuary$estuary == "Gironde"), ]$estuary_limit_lon_min &
        {{longitude}} <= GPS_limits_estuary[which(GPS_limits_estuary$estuary == "Gironde"), ]$estuary_limit_lon_max ~ "Gironde",
      
      {{latitude}} >= GPS_limits_estuary[which(GPS_limits_estuary$estuary == "Loire"), ]$estuary_limit_lat_min &
        {{latitude}} <= GPS_limits_estuary[which(GPS_limits_estuary$estuary == "Loire"), ]$estuary_limit_lat_max &
        {{longitude}} >= GPS_limits_estuary[which(GPS_limits_estuary$estuary == "Loire"), ]$estuary_limit_lon_min &
        {{longitude}} <= GPS_limits_estuary[which(GPS_limits_estuary$estuary == "Loire"), ]$estuary_limit_lon_max ~ "Loire",
      
      {{latitude}} >= GPS_limits_estuary[which(GPS_limits_estuary$estuary == "Seine"), ]$estuary_limit_lat_min &
        {{latitude}} <= GPS_limits_estuary[which(GPS_limits_estuary$estuary == "Seine"), ]$estuary_limit_lat_max &
        {{longitude}} >= GPS_limits_estuary[which(GPS_limits_estuary$estuary == "Seine"), ]$estuary_limit_lon_min &
        {{longitude}} <= GPS_limits_estuary[which(GPS_limits_estuary$estuary == "Seine"), ]$estuary_limit_lon_max ~ "Seine",
      TRUE ~ NA
    )
  )  |>
    filter(!is.na(estuary))
  
  return(completed_data)
      
}
```
  
```{r example-get_estuary_from_gps_position}
toy_data_gps <- data.frame(
  station = c(
    "GIR_01", "GIR_02", "GIR_03",
    "LOI_01", "LOI_02", "LOI_03",
    "SEI_01", "SEI_02", "SEI_03"
  ),
  lat = c(
    45.58, 45.52, 45.45,
    47.28, 47.30, 47.25,
    49.47, 49.45, 49.42
  ),
  lon = c(
    -0.95, -1.05, -1.15,
    -2.05, -2.20, -2.35,
    0.18, 0.30, 0.42
  )
)

get_estuary_from_gps_position(data = toy_data_gps, latitude = lat, longitude = lon)
```

# get_haline_zone_from_gps_position
    
```{r function-get_haline_zone_from_gps_position}
#' Get haline_zone variable from GPS positions
#' 
#' @param data tibble containing columns with GPS position through latitude and longitude columns
#' @param latitude name of latitude column
#' @param longitude name of longitude column
#'
#' @return the tibble + variable haline_zone
#' 
#' @export

get_haline_zone_from_gps_position <- function(data, latitude, longitude){
  
  completed_data <- data |>
    
    # ---- Add haline_zone variable ----
  mutate(
    haline_zone = case_when(
      estuary == "Gironde" &
        {{latitude}} >= GPS_limits_haline[which(GPS_limits_haline$estuary == "Gironde"), ]$halin_limit_lat ~ "outer",
      estuary == "Gironde" &
        {{latitude}} < GPS_limits_haline[which(GPS_limits_haline$estuary == "Gironde"), ]$halin_limit_lat ~ "inner",
      estuary == "Loire" &
        {{longitude}} <= GPS_limits_haline[which(GPS_limits_haline$estuary == "Loire"), ]$halin_limit_lon ~ "outer",
      estuary == "Loire" &
        {{longitude}} > GPS_limits_haline[which(GPS_limits_haline$estuary == "Loire"), ]$halin_limit_lon ~ "inner",
      estuary == "Seine" &
        {{longitude}} <= GPS_limits_haline[which(GPS_limits_haline$estuary == "Seine"), ]$halin_limit_lon ~ "outer",
      estuary == "Seine" &
        {{longitude}} > GPS_limits_haline[which(GPS_limits_haline$estuary == "Seine"), ]$halin_limit_lon ~ "inner",
      TRUE ~ NA
    )
  )
  
  return(completed_data)
      
}
```
  
```{r example-get_haline_zone_from_gps_position}
toy_data_gps <- data.frame(
  estuary = c(
    "Gironde", "Gironde", "Gironde",
    "Loire", "Loire", "Loire",
    "Seine", "Seine", "Seine"
  ),
  lat = c(
    45.58, 45.52, 45.45,
    47.28, 47.30, 47.25,
    49.47, 49.45, 49.42
  ),
  lon = c(
    -0.95, -1.05, -1.15,
    -2.05, -2.20, -2.35,
    0.18, 0.30, 0.42
  )
)

get_haline_zone_from_gps_position(data = toy_data_gps, latitude = lat, longitude = lon)
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_utils.Rmd", vignette_name = NULL, check = FALSE)
```

