---
title: "flat_POMET.Rmd"
output: html_document
editor_options: 
  chunk_output_type: console
---

# fct_formatting_raw_data_pomet

```{r function-fct_formatting_raw_data_pomet}
#' Formatting POMET raw datasets
#'
#' @param data_POMET
#'
#' @import dplyr
#' @import stringr
#' @returns tibble
#' @export
#'
#' @examples
fct_formatting_raw_data_POMET <- function(data_POMET){

  formatted_data_POMET <- data_POMET |>

    # ---- Select species ----
  filter(nom %in% c("Solea solea", "Solea senegalensis",
                    "Dicentrarchus labrax",
                    "Palaemon longirostris", "Crangon crangon")) |>

    # ---- Select variables ----
  select(-c(engin, distance_chalutee, phylum, nom, nom_fr, famille, genre,
            espece_id, Ecological_guild, Position_guild, Trophic_guild, trophic_index_fishbase)) |>

    # ---- Join with traits information ----
  left_join(data_POMET_traits, by = "trait_id") |>

    # ---- Create GPS central position of traits ----
  mutate(latitude = (pos_deb_lat_dd + pos_fin_lat_dd) / 2) |>
    mutate(longitude = (pos_deb_long_dd + pos_fin_long_dd) / 2) |>

    # ----- Create estuary variable -----
  mutate(estuary = case_when(
    masse_eau |> str_starts("Gironde") ~ "Gironde",
    masse_eau |> str_starts("Loire") ~ "Loire",
    masse_eau |> str_starts("Seine") ~ "Seine",
    TRUE ~ NA
  )) |>
    select(-masse_eau) |>

    # ----- Filter estuaries GPS delimitations -----
  mutate(
    estuary = case_when(
      estuary == "Gironde" & latitude > 45.0 & latitude < 45.7 & longitude < -0.6 & longitude > -1.1 ~ "Gironde",
      estuary == "Loire" & latitude > 47.22 & latitude < 47.34 & longitude < -1.8 & longitude > -2.3 ~ "Loire",
      estuary == "Seine" &
        latitude > 49.4 & longitude < 0.5 ~ "Seine",
      TRUE ~ NA
    )
  )  |>

    # ----- Create haline_zone variable -----
  mutate(haline_zone = case_when(
    estuary == "Gironde" & latitude >= 45.4 ~ "polyhalin",
    estuary == "Gironde" & latitude >= 45.0 ~ "mesohalin",
    estuary == "Loire" & longitude <= -2.0 ~ "polyhalin",
    estuary == "Loire" & longitude <= -1.8 ~ "mesohalin",
    estuary == "Seine" & longitude <= 0.3 ~ "polyhalin",
    estuary == "Seine" & longitude <= 0.5 ~ "mesohalin",
    TRUE ~ NA
  )) |>

    # ----- Filter unrelevant observations -----
  filter(trait_id != 82) |> # fleuve Gironde
    filter(trait_id %!in% c(6185, 8494)) |>  # out of Loire
    filter(trait_id %!in% c(13477, 16087, 14362)) # filandres Seine

  return(formatted_data_POMET)
}
```

# fct_size_class

```{r function-fct_size_class}
#' fct_size_class Title
#'
#' @param data 
#' @param species 
#'
#' @import dplyr
#' @importFrom mixtools normalmixEM
#' @return 1
#' @export
#'
#' @examples
fct_size_class <- function(data, species){

  # ----- filter species lengths -----
  lengths <- data |>
    filter(name == species) |>
    filter(saison == "automne") |>
    drop_na(longueur) |>
    pull(longueur)

  # ----- fit mixture model -----
  mix <- mixtools::normalmixEM(lengths, k = 2, maxit = 1000, epsilon = 1e-8)

  # ----- Grid of values -----
  xgrid <- tibble(
    x = seq(min(lengths), max(lengths), length.out = 5000)
  )

  # ----- Weighted densities -----
  densities <- xgrid |>
    mutate(
      dens1 = mix$lambda[1] * dnorm(x, mix$mu[1], mix$sigma[1]),
      dens2 = mix$lambda[2] * dnorm(x, mix$mu[2], mix$sigma[2]),
      dens_tot = dens1 + dens2
    )

  i1 <- which.max(densities$dens1)
  i2 <- which.max(densities$dens2)

  i_min <- min(i1, i2)
  i_max <- max(i1, i2)

  idx_valley <- i_min + which.min(densities$dens_tot[i_min:i_max]) - 1
  size_threshold <- densities$x[idx_valley]

  # ----- Graph -----

  dens_long <- densities |>
    select(x, dens1, dens2)  |>
    pivot_longer(-x, names_to = "groupe", values_to = "densite")

  gg_size_class <- ggplot() +
    # Histogram
    geom_histogram(
      aes(x = lengths, y = after_stat(density)),
      bins = 40,
      fill = "grey80",
      color = "white"
    ) +

    # Gaussian
    geom_line(
      data = dens_long,
      aes(x = x, y = densite, color = groupe),
      linewidth = 1.2
    ) +

    # Threshold
    geom_vline(
      xintercept = size_threshold,
      linetype = "dashed",
      linewidth = 1,
      color = "purple"
    ) +

    # Colors for size classes
    scale_color_manual(
      values = c("dens1" = "red", "dens2" = "blue"),
      labels = c("G0", "G1"),
      name = "Distribution"
    ) +

    # Annotate threshold
    annotate("label",
             x = Inf,
             y = Inf,
             label = paste0("Threshold = ", round(size_threshold), "mm"),
             size = 4,
             hjust = 1.1,
             vjust = 1.1,
             fill = "white",
             color = "purple") +

    # Labels
    labs(
      x = "Length (mm)",
      y = "Density",
      title = paste0("Gaussian mixture and separation thresholds - ", species)
    ) +
    theme_esteem()

  # ----- Function output -----
  return(list(
    gg_size = gg_size_class,
    size_threshold = size_threshold
    ))
}
```

# fusen::inflate()

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_POMET.Rmd", vignette_name = NULL, check = FALSE)
```

