---
title: "flat_data_benthos.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# gg_map_parametre_data_benthos
  
```{r function-gg_map_parametre_data_benthos}
#' Get map of REBENT sampling points for each year of monitoring.
#' 
#' @param data tibble data benthos with ESTUARY, YEAR, LIEU_MNEMONIQUE, latitude, longitude
#' @param estuary character "Gironde", "Loire", or "Seine"
#' @param color character color
#'
#' @return ggplot 1 map per year
#' 
#' @import dplyr
#' @import ggplot2
#' @importFrom sf st_as_sf
#' @importFrom sf st_bbox
#' @importFrom sf st_drop_geometry
#' 
#' @export
gg_map_parametre_data_benthos <- function(data, estuaire, color) {
  
  # Convert to spatial object
  points_sf <- sf::st_as_sf(data, coords = c("longitude", "latitude"), crs = 4326) |>
    filter(ESTUARY == estuaire)
  
  # Define spatial window around points
  bbox <- st_bbox(points_sf)
  marge <- 0.1
  xlim <- c(bbox["xmin"] - marge, bbox["xmax"] + marge)
  ylim <- c(bbox["ymin"] - marge, bbox["ymax"] + marge)
  
  # Create a table with annotations: number of points per year
  annot_df <- points_sf |>
    st_drop_geometry() |>
    group_by(YEAR) |>
    summarise(n = n()) |>
    mutate(
      label = paste("n =", n),
      longitude = xlim[1] + 0.01,  # Fix position
      latitude = ylim[2] - 0.01
    )
  
  # Plot
  plot <- ggplot() +
    geom_sf(data = esteem.overview::fr_map, fill = "grey95", color = "grey50") +
    geom_sf(data = points_sf, size = 1, color = color) +
    geom_text(data = annot_df, aes(x = longitude, y = latitude, label = label), 
              inherit.aes = FALSE, hjust = 0, vjust = 1, size = 4, fontface = "bold") +
    coord_sf(xlim = xlim, ylim = ylim, expand = FALSE) +
    facet_wrap(vars(YEAR)) +
    labs(title = estuaire) +
    theme_minimal()
  
  return(plot)
}
```
  
```{r example-gg_map_parametre_data_benthos}
# gg_map_parametre_data_benthos()
```
  
```{r tests-gg_map_parametre_data_benthos}
test_that("gg_map_parametre_data_benthos works", {
  expect_true(inherits(gg_map_parametre_data_benthos, "function")) 
})
```
  


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_data_benthos.Rmd", vignette_name = NULL, check = FALSE)
```
