---
title: "data_sediment"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{data_sediment}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(esteem.overview)
library(tidyverse, quietly = TRUE)
```

## Select sediment from samples studied for biota
```{r}
data <- esteem.overview::data_sediment |> drop_na(tidal)
```

## Organic matter
```{r}
data_MO <- data |> 
  filter(PARAMETRE_LIBELLE == "Matière organique")
```

```{r}
data_MO_summarised <- data_MO |> 
  group_by(ESTUARY, YEAR, tidal) |> 
  summarise(median_MO = median(RESULTAT))
```


```{r}
ggplot_MO <- ggplot(data_MO_summarised) +
  aes(x = YEAR, y = median_MO, colour = ESTUARY, shape = tidal, linetype = tidal) +
  geom_point() +
  geom_line() +
  labs(y = "Organic matter (%)", x = NULL)

ggplot_MO

ggsave(plot = ggplot_MO, "../inst/results/data_benthos/sediment/organic_matter_year.jpg")
```

```{r}
data_MO_general <- data_MO |> 
  group_by(ESTUARY, tidal) |> 
  summarise(median_MO = median(RESULTAT),
            Q1 = quantile(RESULTAT, probs = 0.25),
            Q3 = quantile(RESULTAT, probs = 0.75))

data_MO_general
```

## Grain size

### Year effect

=> grain size composition is similar between years

```{r}
data_summarised <- data |> 
  filter(PARAMETRE_LIBELLE != "Matière organique") |> 
  group_by(ESTUARY, tidal, YEAR, PARAMETRE_LIBELLE) |> 
  summarise(median_res = median(RESULTAT), .groups = "drop") |> 
  filter(median_res >= 2)

data_size_resume <- data_summarised |> 
  arrange(ESTUARY, tidal, YEAR, desc(median_res)) |> 
  mutate(mid_class = case_when(
    PARAMETRE_LIBELLE == "Fraction < 63 µm" ~ 63,
    PARAMETRE_LIBELLE == "Fraction de 63 à 80 µm" ~ 71,
    PARAMETRE_LIBELLE == "Fraction de 63 à 125 µm" ~ 94,
    PARAMETRE_LIBELLE == "Fraction de 80 à 100 µm" ~ 90,
    PARAMETRE_LIBELLE == "Fraction de 100 à 125 µm" ~ 112,
    PARAMETRE_LIBELLE == "Fraction de 125 à 250 µm" ~ 187,
    PARAMETRE_LIBELLE == "Fraction de 125 à 160 µm" ~ 142,
    PARAMETRE_LIBELLE == "Fraction de 160 à 200 µm" ~ 180,
    PARAMETRE_LIBELLE == "Fraction de 200 à 250 µm" ~ 225,
    PARAMETRE_LIBELLE == "Fraction de 250 à 315 µm" ~ 282,
    PARAMETRE_LIBELLE == "Fraction de 250 à 500 µm" ~ 375,
    PARAMETRE_LIBELLE == "Fraction de 315 à 400 µm" ~ 357,
    PARAMETRE_LIBELLE == "Fraction de 400 à 500 µm" ~ 450,
    PARAMETRE_LIBELLE == "Fraction de 500 à 630 µm" ~ 565,
    PARAMETRE_LIBELLE == "Fraction de 630 à 800 µm" ~ 715,
    PARAMETRE_LIBELLE == "Fraction de 800 µm à 1 mm" ~ 900,
    PARAMETRE_LIBELLE == "Fraction de 1 mm à 1,25 mm" ~ 1125,
    PARAMETRE_LIBELLE == "Fraction de 1,25 à 1,6 mm" ~ 1425,
    PARAMETRE_LIBELLE == "Fraction de 1,6 à 2 mm" ~ 1800,
    PARAMETRE_LIBELLE == "Fraction de 2 à 2,5 mm" ~ 2250,
    PARAMETRE_LIBELLE == "Fraction de 2,5 à 3,15 mm" ~ 2825,
    PARAMETRE_LIBELLE == "Fraction de 2 à 4 mm" ~ 3000
  ))
data_size_resume

ggplot_grain_size_gironde <- data_size_resume |> 
   filter(ESTUARY == "Gironde") |> 
  ggplot() + 
  aes(x = mid_class, y = median_res) +
  geom_col(position = "dodge") +
  facet_grid(rows = vars(YEAR), cols = vars(tidal), scales = "free_x") + 
  labs(title = "Gironde estuary", x = "Grain size (µm)", y = "Proportion in the sediment (%)")
ggsave(plot = ggplot_grain_size_gironde, "../inst/results/data_benthos/sediment/ggplot_grain_size_gironde.jpg")

ggplot_grain_size_loire <- data_size_resume |> 
   filter(ESTUARY == "Loire") |> 
  ggplot() + 
  aes(x = mid_class, y = median_res) +
  geom_col(position = "dodge") +
  facet_grid(rows = vars(YEAR), cols = vars(tidal), scales = "free_x") + 
  labs(title = "Loire estuary", x = "Grain size (µm)", y = "Proportion in the sediment (%)")
ggsave(plot = ggplot_grain_size_loire, "../inst/results/data_benthos/sediment/ggplot_grain_size_loire.jpg")

ggplot_grain_size_seine <- data_size_resume |> 
   filter(ESTUARY == "Seine") |> 
  ggplot() + 
  aes(x = mid_class, y = median_res) +
  geom_col(position = "dodge") +
  facet_grid(rows = vars(YEAR), cols = vars(tidal), scales = "free_x") + 
  labs(title = "Seine estuary", x = "Grain size (µm)", y = "Proportion in the sediment (%)")
ggsave(plot = ggplot_grain_size_seine, "../inst/results/data_benthos/sediment/ggplot_grain_size_seine.jpg")
```

### Summarization by estuary, tidal level and grain size
```{r}
data_summarised <- data |> 
  filter(PARAMETRE_LIBELLE != "Matière organique") |> 
  group_by(ESTUARY, tidal, PARAMETRE_LIBELLE) |> 
  summarise(median_res = median(RESULTAT), .groups = "drop") |> 
  filter(median_res >= 2)
```

```{r}
# data_summarised |> 
#   distinct(PARAMETRE_LIBELLE)

data_size_resume <- data_summarised |> 
  arrange(ESTUARY, tidal, desc(median_res)) |> 
  mutate(mid_class = case_when(
    PARAMETRE_LIBELLE == "Fraction < 63 µm" ~ 63,
    PARAMETRE_LIBELLE == "Fraction de 63 à 125 µm" ~ 94,
    PARAMETRE_LIBELLE == "Fraction de 80 à 100 µm" ~ 90,
    PARAMETRE_LIBELLE == "Fraction de 100 à 125 µm" ~ 112,
    PARAMETRE_LIBELLE == "Fraction de 125 à 250 µm" ~ 187,
    PARAMETRE_LIBELLE == "Fraction de 125 à 160 µm" ~ 142,
    PARAMETRE_LIBELLE == "Fraction de 160 à 200 µm" ~ 180,
    PARAMETRE_LIBELLE == "Fraction de 200 à 250 µm" ~ 225,
    PARAMETRE_LIBELLE == "Fraction de 250 à 315 µm" ~ 282,
    PARAMETRE_LIBELLE == "Fraction de 315 à 400 µm" ~ 357,
    PARAMETRE_LIBELLE == "Fraction de 400 à 500 µm" ~ 450,
    PARAMETRE_LIBELLE == "Fraction de 500 à 630 µm" ~ 565,
    PARAMETRE_LIBELLE == "Fraction de 630 à 800 µm" ~ 715,
    PARAMETRE_LIBELLE == "Fraction de 800 µm à 1 mm" ~ 900,
    PARAMETRE_LIBELLE == "Fraction de 1 mm à 1,25 mm" ~ 1125,
    PARAMETRE_LIBELLE == "Fraction de 1,25 à 1,6 mm" ~ 1425,
    PARAMETRE_LIBELLE == "Fraction de 1,6 à 2 mm" ~ 1800,
    PARAMETRE_LIBELLE == "Fraction de 2 à 4 mm" ~ 3000
  ))
data_size_resume
```

```{r}
ggplot_grain_size <- data_size_resume |> 
  ggplot() + 
  aes(x = mid_class, y = median_res) +
  geom_col() +
  facet_grid(rows = vars(ESTUARY), cols = vars(tidal), scales = "free_x") + 
  labs(x = "Grain size (µm)", y = "Proportion in the sediment (%)")

ggplot_grain_size

ggsave(plot = ggplot_grain_size, "../inst/results/data_benthos/sediment/sediment_grain_size.jpg")
```


