---
title: "data_physico_chimie"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{data_physico_chimie}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
library(esteem.overview)
library(tidyverse)

# ACP
library(FactoMineR)
library(factoextra)
library(missMDA) # missing values handling
```

# Get raw physico-chemical data
```{r}
data <- esteem.overview::data_physchem
```

# Yearly summarized graphical representation

## Compute yearly RESULTAT
```{r}
data_summarized <- data |> 
  mutate(YEAR = year(DATE)) |> 
  mutate(ESTUARY = as.factor(ESTUARY)) |> 
  group_by(ESTUARY, YEAR, PARAMETRE_LIBELLE, PROGRAMME) |> 
  summarise(RESULTAT = median(RESULTAT, na.rm = TRUE), .groups = "drop")
```

```{r}
ggplot_data_summarized <- data_summarized |> 
  ggplot() +
  aes(x = YEAR, y = RESULTAT, colour = ESTUARY) +
  geom_line() +
  facet_grid(rows = vars(PARAMETRE_LIBELLE), scales = "free_y")
ggplot_data_summarized

ggsave(plot = ggplot_data_summarized, filename =  "../inst/results/data_physico_chemistry/ggplot_yearly_summarized_physiochem_parameters.jpg", 
       width = 10, height = 25, units = "cm")
```

## Start and end of measurments
```{r}
data_summarized |> 
  group_by(ESTUARY, PARAMETRE_LIBELLE, PROGRAMME) |> 
  summarise(min_year = min(YEAR),
            max_year = max(YEAR)) |> 
  arrange(PARAMETRE_LIBELLE)
```

# Simple PCA
```{r}
data_summarized_wide <- data_summarized |> 
  pivot_wider(names_from = PARAMETRE_LIBELLE, values_from = RESULTAT) |> 
  mutate(DECADE = case_when(
    YEAR %in% c(1970:1979) ~ "1970's",
    YEAR %in% c(1980:1989) ~ "1980's",
    YEAR %in% c(1990:1999) ~ "1990's",
    YEAR %in% c(2000:2009) ~ "2000's",
    YEAR %in% c(2010:2019) ~ "2010's",
    YEAR %in% c(2020:2029) ~ "2020's",
  ))
```

```{r}
# Get only numerical values for PCA
data_summarized_wide_num <- data_summarized_wide[, sapply(data_summarized_wide, is.numeric)]
group_var_1 <- data_summarized_wide$ESTUARY
group_var_2 <- data_summarized_wide$DECADE |> as.factor()

# Estimating the number of optimal components
nb_comp <- estim_ncpPCA(data_summarized_wide_num, method = "Regularized")$ncp
# Mixed NA allocation with the right number of components
df_num_imp <- imputePCA(data_summarized_wide_num, ncp = nb_comp)

# Compute PCA
res_pca <- FactoMineR::PCA(df_num_imp$completeObs,
               scale.unit = TRUE,
               graph = TRUE)
```


```{r}
# Variables graph
pca_physicochemistry_var <- fviz_pca_var(
  res_pca,
  col.var = "contrib",
  # couleur = contribution à l'axe
  gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
  repel = TRUE,
  title = "PCA variables"
)
pca_physicochemistry_var

ggsave(plot = pca_physicochemistry_var, filename = "../inst/results/data_physico_chemistry/PCA/ggplot_PCA_variables.jpg", 
       width = 20, height = 20, units = "cm")
```


```{r}
# Individual ESTUARY graph
pca_physicochemistry_ind_ESTUARY <- fviz_pca_ind(
  res_pca,
  habillage = group_var_1, 
  palette = "jco",
  addEllipses = TRUE, 
  ellipse.type = "confidence",
  title = "PCA individuals by estuary"
)
pca_physicochemistry_ind_ESTUARY

ggsave(plot = pca_physicochemistry_ind_ESTUARY, filename = "../inst/results/data_physico_chemistry/PCA/ggplot_PCA_ind_estuary.jpg", 
       width = 20, height = 20, units = "cm")
```


```{r}
# Individual DECADE graph
pca_physicochemistry_ind_DECADE <- fviz_pca_ind(
  res_pca,
  habillage = group_var_2, 
  palette = "jco",
  addEllipses = TRUE, 
  ellipse.type = "confidence",
  title = "PCA individuals by decade"
)
pca_physicochemistry_ind_DECADE

ggsave(plot = pca_physicochemistry_ind_DECADE, filename = "../inst/results/data_physico_chemistry/PCA/ggplot_PCA_ind_decade.jpg", 
       width = 20, height = 20, units = "cm")
```

```{r}
# Individual ESTUARY & DECADE graph
df_res_pca <- as.data.frame(res_pca$ind$coord)
df_res_pca$ESTUARY <- group_var_1
df_res_pca$DECADE <- group_var_2

pca_physicochemistry_ind_ESTUARY_DECADE <- ggplot(df_res_pca, aes(x = Dim.1, y = Dim.2, color = ESTUARY, shape = DECADE)) +
  geom_point(size = 3) +
  stat_ellipse(aes(group = interaction(ESTUARY, DECADE)), type = "norm", linetype = 2) +
  theme_minimal() +
  labs(title = "PCA with double grouping: estuary and decade", x = "Dim 1", y = "Dim 2")
pca_physicochemistry_ind_ESTUARY_DECADE

ggsave(plot = pca_physicochemistry_ind_ESTUARY_DECADE, filename = "../inst/results/data_physico_chemistry/PCA/ggplot_PCA_ind_estuary_decade.jpg", 
       width = 20, height = 20, units = "cm")
```

## cos²
```{r}
fviz_pca_var(res_pca, col.var = "cos2") # variables
```


```{r}
fviz_pca_ind(res_pca, col.ind = "cos2") # individus
```
```{r}
fviz_pca_ind(res_pca, col.ind = "contrib")
```


# Nitrogen cycle

Compute the sum of nitrite + nitrate
```{r}
data_summarized_N0 <- data_summarized |> 
  pivot_wider(names_from = PARAMETRE_LIBELLE, values_from = RESULTAT) |> 
  mutate(sumNO2NO3 = `Azote nitreux (nitrite)` + `Azote nitrique (nitrate)`) |> 
  pivot_longer(cols = -c(ESTUARY, YEAR), 
               names_to = "PARAMETRE_LIBELLE", values_to = "RESULTAT")
```

Compare the computed sum levels with existing sum
```{r}
data_N0sum_comparison <- data_summarized_N0 |> 
  filter(PARAMETRE_LIBELLE %in% c("sumNO2NO3", "Nitrate + nitrite"))

ggplot_N0sum_comparison <- ggplot(data_N0sum_comparison) +
  aes(x = YEAR, y = RESULTAT, colour = PARAMETRE_LIBELLE) +
  geom_line() +
  facet_grid(rows = vars(ESTUARY))
ggplot_N0sum_comparison

ggsave(plot = ggplot_N0sum_comparison, filename = "../inst/results/data_physico_chemistry/ggplot_nitrogen_sum_comparison.jpg",width = 15, height = 10, units = "cm")
```


```{r}
data_nitrogen_cycle <- data_summarized_N0 |> 
  pivot_wider(names_from = PARAMETRE_LIBELLE, values_from = RESULTAT) |> 
  group_by(ESTUARY, YEAR) |> 
  mutate(max_NO2NO3 = max(sumNO2NO3, `Nitrate + nitrite`, na.rm = TRUE)) |> 
  ungroup() |> 
  mutate(nitrogen_indicator = Ammonium / max_NO2NO3) |> 
  pivot_longer(cols = -c(ESTUARY, YEAR), 
               names_to = "PARAMETRE_LIBELLE", values_to = "RESULTAT")

data_N_indicator <- data_nitrogen_cycle |> 
  filter(PARAMETRE_LIBELLE == "nitrogen_indicator")

ggplot_data_N_indicator <- ggplot(data_N_indicator) +
  aes(x = YEAR, y = RESULTAT, colour = ESTUARY) +
  geom_line()
ggplot_data_N_indicator

ggsave(plot = ggplot_data_N_indicator, filename = "../inst/results/data_physico_chemistry/ggplot_nitrogen_cycle_indicator.jpg",width = 15, height = 10, units = "cm")
```

# Primary production activity

Compute pheopigment/chlorophyl

```{r}
data_summarized_p1 <- data_summarized |> 
  pivot_wider(names_from = PARAMETRE_LIBELLE, values_from = RESULTAT) |> 
  mutate(p1_indicator = Phéopigments / `Chlorophylle a`) |> 
  pivot_longer(cols = -c(ESTUARY, YEAR), 
               names_to = "PARAMETRE_LIBELLE", values_to = "RESULTAT")

data_p1 <- data_summarized_p1 |> 
  filter(PARAMETRE_LIBELLE == "p1_indicator")

ggplot_data_p1 <- ggplot(data_p1) +
  aes(x = YEAR, y = RESULTAT, colour = ESTUARY) +
  geom_line()
ggplot_data_p1

ggsave(plot = ggplot_data_p1, filename = "../inst/results/data_physico_chemistry/ggplot_primary_prod.jpg",width = 15, height = 10, units = "cm")
```


