---
title: "data_contamination_tributyltin"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{data_contamination_tributyltin}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
library(esteem.overview)
library(tidyverse)
library(here)
```

# Get raw data for tributyltin cation => thresholds in ng/g dw
```{r}
tributyltin <- data.frame(PARAMETRE_LIBELLE = "Tributyltin cation",
                   EAC_ng_gdw = 12)

data_tributyltin <- esteem.overview::data_ROCCHMV_cleaned |> ungroup() |>
  filter(support == "Bivalve") |>
  select(-c(SUPPORT_NIVEAU_PRELEVEMENT, support, niveau)) |>
  mutate(PARAMETRE_LIBELLE = case_when(
    PARAMETRE_LIBELLE == "Tributylétain cation" ~ "Tributyltin cation"
  )) |> 
  filter(PARAMETRE_LIBELLE %in% tributyltin$PARAMETRE_LIBELLE) |>
  left_join(esteem.overview::data_ROCCHMV_bio, by = "ESTUARY")
```

## Get the same unit of measurment

Different units:

- 2019-2020: µg/(kg MS)
- 2021-2024: µg.kg-1, p.h.
```{r}
data_tributyltin |>
  distinct(UNITE)

# data_tributyltin |>
#   mutate(YEAR = as.factor(YEAR)) |>
#   distinct(YEAR, UNITE, ESTUARY, PARAMETRE_LIBELLE) |>  View(title = "tributyltin units")
```

Transform all results in ng/g dw (same as µg/kg):
```{r}
data_tributyltin_dw <- data_tributyltin |>
  # transformation into dw concentrations
  mutate(RESULTAT = case_when(
    UNITE == "µg.kg-1, p.h." ~ RESULTAT / (`Matière sèche_%` / 100),
    UNITE == "µg/(kg MS)" ~ RESULTAT ,
  )) |>
  # Change to unified unit
  mutate(UNITE = "ng/g dw") |>
  # Get only one value per year
  group_by(ESTUARY, YEAR, PARAMETRE_LIBELLE) |>
  mutate(RESULTAT = mean(RESULTAT)) |>
  ungroup() |>
  # Round result values
  mutate(RESULTAT = round(RESULTAT, digits = 3))

```

# Time series graphs

## Spearman's correlation coefficient + test
```{r}
# Compute for all time serie
data_tributyltin_dw <- data_tributyltin_dw |> 
  mutate(last_trend = "Last 15 years")

res_tributyltin_dw_trends <- get_last_trend_info(
  data = data_tributyltin_dw, 
  norm = tributyltin
  )

writexl::write_xlsx(res_tributyltin_dw_trends, "../inst/results/data_contam/tributyltin/recent_trends_tributyltin_dw.xlsx")
```

```{r}
ggplot_tributyltin_dw <- ggplot(data_tributyltin_dw) +
  aes(x = YEAR,
      y = RESULTAT,
      colour = ESTUARY) +
  geom_line() +
  geom_smooth(se = FALSE) +
  theme(legend.position = "bottom") +
  facet_grid(rows = vars(
    fct_relevel(PARAMETRE_LIBELLE, tributyltin$PARAMETRE_LIBELLE)
  ), scales = "free_y") +
  labs(colour = "Estuary", y = "Contamination level \n in ng/g dw", x = NULL) +
# Add last break dates of segmented models and arrows for significant last trends
  geom_text(
    data = res_tributyltin_dw_trends,
    aes(x = max(last_year)+1, y = last_resultat, label = symbol), size = rel(6),
    family = "DejaVu Sans",   # specify the font that contains arrows
    show.legend = FALSE) +
# Add environmental threshold when existing
  geom_text(
    data = res_tributyltin_dw_trends,
    aes(x = max(last_year)+1, y = EAC_ng_gdw +0.5, label = sprintf("%.2f", EAC_ng_gdw)),
    color = "red", size = 2.5
  ) +
  geom_hline(
    data = res_tributyltin_dw_trends,
    aes(yintercept = EAC_ng_gdw),
    color = "red", linetype = "dashed"
  )

ggplot_tributyltin_dw

ggsave(plot = ggplot_tributyltin_dw, "../inst/results/data_contam/tributyltin/ggplot_tributyltin_dw_time_series.jpg",
       width = 10, height = 7, units = "cm")
```

# First vs last period graphs
```{r}
data_tributyltin_dw_norm_relative <- data_tributyltin_dw |>
  left_join(tributyltin) |>
  mutate(RESULTAT = RESULTAT / EAC_ng_gdw * 100)
```

```{r}
plot_tributyltin_dw_periode <- data_tributyltin_dw_norm_relative |>
  ggplot() +
  aes(x = ESTUARY, y = RESULTAT) +
  geom_boxplot(width = 0.6, colour = "deeppink") +
  facet_grid(rows = vars(PARAMETRE_LIBELLE), scales = "free_y") +
  labs(x = NULL, y = "Deviation from limit value \n (% ng/g dw)", colour = "Period") +
  theme(legend.position = "bottom")

plot_tributyltin_dw_periode

ggsave(plot = plot_tributyltin_dw_periode, "../inst/results/data_contam/tributyltin/ggplot_tributyltin_dw_periods.jpg",
       width = 10, height = 7, units = "cm")
```

## General levels of contamination
```{r}
data_tributyltin_dw_levels <- data_tributyltin_dw |> 
  group_by(ESTUARY, PARAMETRE_LIBELLE) |> 
  summarise(median_ng_gdw = median(RESULTAT), .groups = "drop") |> 
  arrange(PARAMETRE_LIBELLE)

data_tributyltin_dw_normrelative <- data_tributyltin_dw_norm_relative |> 
  group_by(ESTUARY, PARAMETRE_LIBELLE) |> 
  summarise(median_percent = median(RESULTAT), .groups = "drop") |> 
  arrange(PARAMETRE_LIBELLE) |>  
  select(ESTUARY, PARAMETRE_LIBELLE, median_percent)

data_tributyltin_general_levels <- full_join(data_tributyltin_dw_levels, data_tributyltin_dw_normrelative)

writexl::write_xlsx(x = data_tributyltin_general_levels, path = "../inst/results/data_contam/tributyltin/summarised_levels_data_tributyltin_dw.xlsx")
```

# General evaluation
```{r}
# trends
res_tributyltin_dw_trends

# color dot from percentage
# blue: [0-50%[, green: [50-100%[, yellow:[100-150%[, orange: [150-300%[, red: [300-500%[, black: > 500%
data_tributyltin_dw_norm_relative |>
  group_by(ESTUARY, PARAMETRE_LIBELLE) |>
  summarise(median = median(RESULTAT))
```

