# WARNING - Generated by {fusen} from dev/flat_data_contamination.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("get_last_trend_info works", {
  expect_true(inherits(get_last_trend_info, "function")) 
})
