# WARNING - Generated by {fusen} from dev/flat_data_contamination.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("fun_seg_model works", {
  expect_true(inherits(fun_seg_model, "function")) 
})
