# WARNING - Generated by {fusen} from dev/flat_data_contamination.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("gg_map_data_contamination_rocchmv works", {
  expect_true(inherits(gg_map_data_contamination_rocchmv, "function")) 
})
