# WARNING - Generated by {fusen} from dev/flat_data_contamination.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("spearman_test works", {
  expect_true(inherits(spearman_test, "function")) 
})
