# WARNING - Generated by {fusen} from dev/flat_data_benthos.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("gg_map_parametre_data_benthos works", {
  expect_true(inherits(gg_map_parametre_data_benthos, "function")) 
})
