# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("ggplot2_colors works", {
  expect_true(inherits(ggplot2_colors, "function")) 
  expect_equal(object = ggplot2_colors(1),
               expected = c("#F8766D"))
})
