# WARNING - Generated by {fusen} from dev/flat_fct_openstreet_base_map.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("fct_openstreet_base_map works", {
  expect_true(inherits(fct_openstreet_base_map, "function"))
})
