# WARNING - Generated by {fusen} from dev/flat_long_term_trends.Rmd: do not edit by hand # nolint: line_length_linter.

#' Create a layout automatically
#' 
#' It determines what to set for `colour`, `facet_rows` and `facet_cols` based on the variables present in `grouping`.
#' 
#' @return
#' 
#' @noRd
auto_plot_layout <- function(group_vars) {
  
  n_vars <- length(group_vars)
  
  if (n_vars == 0) {
    return(list(
      colour_var = NULL,
      facet_rows = NULL,
      facet_cols = NULL
    ))
  }
  
  if (n_vars == 1) {
    return(list(
      colour_var = group_vars[1],
      facet_rows = NULL,
      facet_cols = NULL
    ))
  }
  
  if (n_vars == 2) {
    return(list(
      colour_var = group_vars[2],
      facet_rows = NULL,
      facet_cols = group_vars[1]
    ))
  }
  
  if (n_vars >= 3) {
    return(list(
      colour_var = group_vars[3],
      facet_rows = group_vars[1],
      facet_cols = group_vars[2]
    ))
  }
}
