# WARNING - Generated by {fusen} from dev/flat_ambi.Rmd: do not edit by hand # nolint: line_length_linter.

#' Compute AMBI index for a dataset
#'
#' @param data Data frame with taxon, count, and optionally group
#' @param taxon Column name for taxa
#' @param count Column name for abundance
#' @param group Column name for ecological group (EG I–V)
#'
#' @return AMBI index (numeric)
#' @export
#' @import dplyr
#' @importFrom rlang ensym
#' 
compute_ambi <- function(data, taxon, count, group) {
  
  taxon <- rlang::ensym(taxon)
  count <- rlang::ensym(count)
  group <- rlang::ensym(group)
  
  # Poids AMBI
  data |>
    dplyr::mutate(
      weight = dplyr::case_when(
        !!group == "I"   ~ 0,
        !!group == "II"  ~ 1.5,
        !!group == "III" ~ 3,
        !!group == "IV"  ~ 4.5,
        !!group == "V"   ~ 6,
        TRUE ~ NA_real_
      )
    ) |>
    dplyr::summarise(
      ambi = sum(!!count * weight, na.rm = TRUE) / sum(!!count, na.rm = TRUE)
    ) |>
    dplyr::pull(ambi)
}
