# WARNING - Generated by {fusen} from dev/flat_maps.Rmd: do not edit by hand # nolint: line_length_linter.

#' Create and save OpenStreetMap base map for an estuary
#'
#' @param GPS_limits_estuary Data frame containing one row per estuary with latitude/longitude limits
#' @param estuary_name Character name of estuary to build
#' @param villes_selection Character vector of city names to keep (optional)
#' @param path Base path for saving (default: inst/extdata/basemaps)
#' @param buffer_deg Numeric buffer added around bbox in decimal degrees
#'
#' @return A list with map components (also saved on disk)
#'
#' @import dplyr
#' @importFrom sf st_bbox st_polygon st_sf st_sfc st_as_sfc
#' @importFrom sf st_intersection st_write
#' @importFrom osmdata opq add_osm_feature osmdata_sf
#' @importFrom maptiles get_tiles
#' @importFrom terra writeRaster
#' @export
fct_build_and_save_basemap <- function(GPS_limits_estuary,
                                       estuary_name,
                                       villes_selection = NULL,
                                       path = "inst/extdata/basemaps",
                                       buffer_deg = 0.02) {

  # -------------------------
  # 1. Get estuary limits
  # -------------------------
  estuary_limits <- GPS_limits_estuary |>
    dplyr::filter(estuary == estuary_name)

  if (nrow(estuary_limits) == 0) {
    stop("No limits found for estuary: ", estuary_name)
  }

  if (nrow(estuary_limits) > 1) {
    stop("More than one row found for estuary: ", estuary_name)
  }

  required_cols <- c(
    "estuary_limit_lat_min",
    "estuary_limit_lat_max",
    "estuary_limit_lon_min",
    "estuary_limit_lon_max"
  )

  missing_cols <- setdiff(required_cols, names(estuary_limits))

  if (length(missing_cols) > 0) {
    stop(
      "Missing required columns: ",
      paste(missing_cols, collapse = ", ")
    )
  }

  # -------------------------
  # 2. Bounding box + buffer
  # -------------------------
  xlim <- c(
    estuary_limits$estuary_limit_lon_min - buffer_deg,
    estuary_limits$estuary_limit_lon_max + buffer_deg
  )

  ylim <- c(
    estuary_limits$estuary_limit_lat_min - buffer_deg,
    estuary_limits$estuary_limit_lat_max + buffer_deg
  )

  fixed_bbox <- fix_bbox_aspect(
    xlim = xlim,
    ylim = ylim,
    target_ratio = 1 # carte carrée
  )

  xlim <- fixed_bbox$xlim
  ylim <- fixed_bbox$ylim

  coords <- matrix(
    c(
      xlim[1], ylim[1],
      xlim[1], ylim[2],
      xlim[2], ylim[2],
      xlim[2], ylim[1],
      xlim[1], ylim[1]
    ),
    ncol = 2,
    byrow = TRUE
  )

  bbox_sf <- sf::st_sf(
    geometry = sf::st_sfc(
      sf::st_polygon(list(coords)),
      crs = 4326
    )
  )

  bbox_vector <- c(
    xmin = xlim[1],
    ymin = ylim[1],
    xmax = xlim[2],
    ymax = ylim[2]
  )

  # -------------------------
  # 3. OSM cities
  # -------------------------
  villes_osm <- osmdata::opq(bbox = bbox_vector) |>
    osmdata::add_osm_feature(
      key = "place",
      value = c("city", "town", "village")
    ) |>
    osmdata::osmdata_sf()

  villes_points <- villes_osm$osm_points

  if (!is.null(villes_points) && nrow(villes_points) > 0) {

    villes_points <- sf::st_intersection(
      villes_points,
      sf::st_as_sfc(sf::st_bbox(bbox_sf))
    )

    # -------------------------
    # Filter by selected city names
    # -------------------------
    if (!is.null(villes_selection)) {

      villes_points <- villes_points |>
        dplyr::filter(name %in% villes_selection)

      villes_manquantes <- setdiff(
        villes_selection,
        unique(villes_points$name)
      )

      if (length(villes_manquantes) > 0) {
        warning(
          "These cities were not found in OSM data: ",
          paste(villes_manquantes, collapse = ", ")
        )
      }
    }

    villes_finales <- villes_points

  } else {
    villes_finales <- NULL
  }

  # -------------------------
  # 4. Download OSM raster
  # -------------------------
  osm_raster <- maptiles::get_tiles(
    bbox_sf,
    provider = "OpenStreetMap",
    crop = TRUE
  )

  # matérialisation pour éviter external pointer
  osm_raster <- terra::writeRaster(
    osm_raster,
    filename = tempfile(fileext = ".tif"),
    overwrite = TRUE
  )

  # -------------------------
  # 5. Save to package
  # -------------------------
  dir_estuary <- file.path(path, estuary_name)

  dir.create(
    dir_estuary,
    recursive = TRUE,
    showWarnings = FALSE
  )

  terra::writeRaster(
    osm_raster,
    filename = file.path(dir_estuary, "osm.tif"),
    overwrite = TRUE
  )

  if (!is.null(villes_finales)) {
    sf::st_write(
      villes_finales,
      file.path(dir_estuary, "villes.gpkg"),
      delete_dsn = TRUE,
      quiet = TRUE
    )
  }

  saveRDS(
    list(xlim = xlim, ylim = ylim),
    file.path(dir_estuary, "bbox.rds")
  )

  # -------------------------
  # 6. Return object
  # -------------------------
  return(list(
    estuary = estuary_name,
    bbox_sf = bbox_sf,
    osm_raster = osm_raster,
    villes = villes_finales,
    xlim = xlim,
    ylim = ylim
  ))
}
