# WARNING - Generated by {fusen} from dev/flat_POMET.Rmd: do not edit by hand # nolint: line_length_linter.

#' Formatting POMET raw datasets
#'
#' @param data_POMET tibble raw dataset from POMET program
#' @param species NULL or chr vector of species (default list: "Solea solea", "Solea senegalensis", "Dicentrarchus "Palaemon longirostris", "Crangon crangon")
#'
#' @import dplyr
#' @import stringr
#' @returns tibble
#' @export
#'
fct_formatting_raw_data_POMET <- function(data_POMET,
                                          species = c(
                                            "Solea solea",
                                            "Solea senegalensis",
                                            "Dicentrarchus labrax",
                                            "Palaemon longirostris",
                                            "Crangon crangon"
                                          )) {
  
  if(is.null(species) == FALSE){
    formatted_data_POMET <- data_POMET |>
    
    # ---- Select species ----
  filter(nom %in% species)
  }else{
    formatted_data_POMET <- data_POMET
  }
  
  formatted_data_POMET <- formatted_data_POMET |>
    
    # ---- Select variables ----
  select(
    -c(
      engin,
      distance_chalutee,
      phylum,
      nom,
      nom_fr,
      famille,
      genre,
      espece_id,
      Ecological_guild,
      Position_guild,
      Trophic_guild,
      trophic_index_fishbase
    )
  ) |>
    
    # ---- Join with traits information ----
  left_join(data_POMET_traits, by = "trait_id")
  
  return(formatted_data_POMET)
}
