# WARNING - Generated by {fusen} from dev/flat_POMET.Rmd: do not edit by hand # nolint: line_length_linter.

#' fct_size_class Title
#'
#' @param data 
#' @param species 
#'
#' @import dplyr
#' @importFrom mixtools normalmixEM
#' @return 1
#' @export
#'
fct_size_class <- function(data, species){

  # ----- filter species lengths -----
  lengths <- data |>
    filter(name == species) |>
    filter(saison == "automne") |>
    drop_na(longueur) |>
    pull(longueur)

  # ----- fit mixture model -----
  mix <- mixtools::normalmixEM(lengths, k = 2, maxit = 1000, epsilon = 1e-8)

  # ----- Grid of values -----
  xgrid <- tibble(
    x = seq(min(lengths), max(lengths), length.out = 5000)
  )

  # ----- Weighted densities -----
  densities <- xgrid |>
    mutate(
      dens1 = mix$lambda[1] * dnorm(x, mix$mu[1], mix$sigma[1]),
      dens2 = mix$lambda[2] * dnorm(x, mix$mu[2], mix$sigma[2]),
      dens_tot = dens1 + dens2
    )

  i1 <- which.max(densities$dens1)
  i2 <- which.max(densities$dens2)

  i_min <- min(i1, i2)
  i_max <- max(i1, i2)

  idx_valley <- i_min + which.min(densities$dens_tot[i_min:i_max]) - 1
  size_threshold <- densities$x[idx_valley]

  # ----- Graph -----

  dens_long <- densities |>
    select(x, dens1, dens2)  |>
    pivot_longer(-x, names_to = "groupe", values_to = "densite")

  gg_size_class <- ggplot() +
    # Histogram
    geom_histogram(
      aes(x = lengths, y = after_stat(density)),
      bins = 40,
      fill = "grey80",
      color = "white"
    ) +

    # Gaussian
    geom_line(
      data = dens_long,
      aes(x = x, y = densite, color = groupe),
      linewidth = 1.2
    ) +

    # Threshold
    geom_vline(
      xintercept = size_threshold,
      linetype = "dashed",
      linewidth = 1,
      color = "purple"
    ) +

    # Colors for size classes
    scale_color_manual(
      values = c("dens1" = "red", "dens2" = "blue"),
      labels = c("G0", "G1"),
      name = "Distribution"
    ) +

    # Annotate threshold
    annotate("label",
             x = Inf,
             y = Inf,
             label = paste0("Threshold = ", round(size_threshold), "mm"),
             size = 4,
             hjust = 1.1,
             vjust = 1.1,
             fill = "white",
             color = "purple") +

    # Labels
    labs(
      x = "Length (mm)",
      y = "Density",
      title = paste0("Gaussian mixture and separation thresholds - ", species)
    ) +
    theme_esteem()

  # ----- Function output -----
  return(list(
    gg_size = gg_size_class,
    size_threshold = size_threshold
    ))
}
