# WARNING - Generated by {fusen} from dev/flat_POMET.Rmd: do not edit by hand # nolint: line_length_linter.

#' Formatting POMET raw datasets
#'
#' @param data_POMET
#'
#' @import dplyr
#' @import stringr
#' @returns tibble
#' @export
#'
fct_formatting_raw_data_POMET <- function(data_POMET){

  formatted_data_POMET <- data_POMET |>

    # ---- Select species ----
  filter(nom %in% c("Solea solea", "Solea senegalensis",
                    "Dicentrarchus labrax",
                    "Palaemon longirostris", "Crangon crangon")) |>

    # ---- Select variables ----
  select(-c(engin, distance_chalutee, phylum, nom, nom_fr, famille, genre,
            espece_id, Ecological_guild, Position_guild, Trophic_guild, trophic_index_fishbase)) |>

    # ---- Join with traits information ----
  left_join(data_POMET_traits, by = "trait_id") |>

    # ---- Create GPS central position of traits ----
  mutate(latitude = (pos_deb_lat_dd + pos_fin_lat_dd) / 2) |>
    mutate(longitude = (pos_deb_long_dd + pos_fin_long_dd) / 2) |>

    # ----- Create estuary variable -----
  mutate(estuary = case_when(
    masse_eau |> str_starts("Gironde") ~ "Gironde",
    masse_eau |> str_starts("Loire") ~ "Loire",
    masse_eau |> str_starts("Seine") ~ "Seine",
    TRUE ~ NA
  )) |>
    select(-masse_eau) |>

    # ----- Filter estuaries GPS delimitations -----
  mutate(
    estuary = case_when(
      estuary == "Gironde" & latitude > 45.0 & latitude < 45.7 & longitude < -0.6 & longitude > -1.1 ~ "Gironde",
      estuary == "Loire" & latitude > 47.22 & latitude < 47.34 & longitude < -1.8 & longitude > -2.3 ~ "Loire",
      estuary == "Seine" &
        latitude > 49.4 & longitude < 0.5 ~ "Seine",
      TRUE ~ NA
    )
  )  |>

    # ----- Create haline_zone variable -----
  mutate(haline_zone = case_when(
    estuary == "Gironde" & latitude >= 45.4 ~ "polyhalin",
    estuary == "Gironde" & latitude >= 45.0 ~ "mesohalin",
    estuary == "Loire" & longitude <= -2.0 ~ "polyhalin",
    estuary == "Loire" & longitude <= -1.8 ~ "mesohalin",
    estuary == "Seine" & longitude <= 0.3 ~ "polyhalin",
    estuary == "Seine" & longitude <= 0.5 ~ "mesohalin",
    TRUE ~ NA
  )) |>

    # ----- Filter unrelevant observations -----
  filter(trait_id != 82) |> # fleuve Gironde
    filter(trait_id %!in% c(6185, 8494)) |>  # out of Loire
    filter(trait_id %!in% c(13477, 16087, 14362)) # filandres Seine

  return(formatted_data_POMET)
}
