# WARNING - Generated by {fusen} from dev/flat_maps.Rmd: do not edit by hand # nolint: line_length_linter.

#' Crop map images
#' 
#' Delete empty space around map ggplots
#' 
#' @param path file path
#'
#' @return a cropped map to be used in cowplot::plot_grid()
#' 
#' @export
#' @examples
#' fct_img_crop()
fct_img_crop <- function(path) {
  ggdraw() +
    draw_image(path) +
    theme(plot.margin = margin(0, 0, 0, 0))
}
