# WARNING - Generated by {fusen} from dev/flat_maps.Rmd: do not edit by hand # nolint: line_length_linter.

#' Filter data subset corresponding of GPS boxes to be studied
#' 
#' @param data tibble with estuary, haline_zone, latitude and longitude variables
#'
#' @return tibble filtered for GPS boxes to be thurther studied
#' 
#' @noRd
filter_studied_gps_boxes <- function(data) {
  filtered_data <- data |>
    filter(
      case_when(
        estuary == "Gironde" & haline_zone == "outer" &
          latitude >= 45.48 &
          latitude < 45.56 & longitude > -1.1 & longitude < -0.9 ~ TRUE,
        estuary == "Gironde" & haline_zone == "inner" &
          latitude >= 45.15 &
          latitude < 45.30 & longitude > -0.8 & longitude < -0.6 ~ TRUE,
        estuary == "Loire" & haline_zone == "outer" &
          latitude >= 47.26 &
          latitude < 47.30 & longitude > -2.2 & longitude < -2.15 ~ TRUE,
        estuary == "Loire" & haline_zone == "inner" &
          latitude >= 47.27 &
          latitude < 47.29 & longitude > -2.0 & longitude < -1.8 ~ TRUE,
        estuary == "Seine" & haline_zone == "outer" &
          latitude >= 49.42 &
          latitude < 49.47 & longitude > 0.07 & longitude < 0.2 ~ TRUE,
        estuary == "Seine" & haline_zone == "inner" &
          latitude >= 49.42 &
          latitude < 49.49 & longitude > 0.2 ~ TRUE,
        TRUE ~ FALSE
      )
    )
  
  return(filtered_data)
}
