# WARNING - Generated by {fusen} from dev/flat_maps.Rmd: do not edit by hand # nolint: line_length_linter.

#' @noRd
fix_bbox_aspect <- function(xlim, ylim, target_ratio = 1) {
  # target_ratio = largeur / hauteur du panneau final
  
  mid_lat <- mean(ylim)
  lon_factor <- cos(mid_lat * pi / 180)
  
  width  <- diff(xlim) * lon_factor
  height <- diff(ylim)
  
  current_ratio <- width / height
  
  if (current_ratio > target_ratio) {
    # bbox trop large -> augmenter la hauteur
    new_height <- width / target_ratio
    delta <- (new_height - height) / 2
    ylim <- ylim + c(-delta, delta)
  } else {
    # bbox trop haute -> augmenter la largeur
    new_width <- height * target_ratio
    delta <- (new_width - width) / lon_factor / 2
    xlim <- xlim + c(-delta, delta)
  }
  
  list(xlim = xlim, ylim = ylim)
}
