# WARNING - Generated by {fusen} from dev/flat_data_contamination.Rmd: do not edit by hand # nolint: line_length_linter.

#' Title
#' 
#' Description
#' 
#' @return
#' 
#' @export
#' @examples
#' # fun_seg_model()
fun_seg_model <- function(data, estuary, chemical, folder = "metals", n_break = 1, plot_save = TRUE){
      
  # Data filtering
  data_estuary_chemical <- data |>  filter(ESTUARY == estuary, PARAMETRE_LIBELLE == chemical)
  
  # Segmented model
  lm_model <- lm(data = data_estuary_chemical, RESULTAT ~ YEAR)
  seg_model <- segmented(lm_model, seg.Z = ~ YEAR, npsi = n_break)
    # summary(seg_model) ## identifies the inflection point and tests whether the model is significant
    # anova(seg_model) ## allows us to see if the inflection is significant
    # slope(seg_model) ## details the slopes
  
  # Put into a data.frame
  slope_df <- slope(seg_model)$YEAR |> as.data.frame()
  colnames(slope_df) <- c("Estimate", "StdErr", "t_value", "CI_lower", "CI_upper")
  rownames(slope_df) <- paste0("Segment ", seq_len(nrow(slope_df)))
  # Calculation of the two-sided p-value
  slope_df$p_value <- 2 * pt(-abs(slope_df$t_value), df = df.residual(seg_model))
  # Breakpoint recovery and conversion to Date
  break_dates <- seg_model$psi[, "Est."]
  # Create segment terminals
  segment_start <- c(min(data_estuary_chemical$YEAR), break_dates)
  segment_end   <- c(break_dates, max(data_estuary_chemical$YEAR))
  # Middle of each segment
  slope_df$mid_date <- (as.numeric(segment_start) + as.numeric(segment_end)) / 2
  # Label text for each segment
  slope_df$label <- paste0(
    "β = ", round(slope_df$Estimate, 3),
    " [", round(slope_df$CI_lower, 3),
    "; ", round(slope_df$CI_upper, 3),
    "] µg/gdw / y", "\n",
    ifelse(slope_df$p_value < 0.05, "p < 0.05", paste0("p = ", signif(slope_df$p_value, 6)))
  )
  
  # Build ggplot
  plot <- ggplot(data_estuary_chemical) +
    aes(x = YEAR, y = RESULTAT) +
    geom_line() +
    geom_line(aes(y = fitted(seg_model)), color = "blue") +
    geom_vline(xintercept = break_dates,
               linetype = "dashed",
               color = "blue") +
    geom_text(data = slope_df,
              aes(x = mid_date, y = max(data_estuary_chemical$RESULTAT), label = label),
      vjust = -0.5, color = "darkgreen", size = 3.5) +
    expand_limits(y = max(data_estuary_chemical$RESULTAT, na.rm = TRUE) * 1.1) +
    labs(title = paste0("Changes in ", chemical, " contamination in the ", estuary, " estuary"),
         x = NULL, y = paste0("Concentration in ", unique(data_estuary_chemical$UNITE)))
  
  # Plot saving
  if(plot_save == TRUE){
      filename <- paste0("segmented_models/ggplot_", chemical, "_", estuary, ".png")
  ggsave(plot = plot, filename = here("inst/results/data_contam/", folder, filename), width = 20, height = 15, units = "cm")
  } else {}

  
  # Table
  tibble(
    ESTUARY = estuary,
    PARAMETRE_LIBELLE = chemical,
    break_dates = break_dates[length(break_dates)],
    last_p_value = slope_df$p_value[length(slope_df$p_value)],
    last_slope = slope_df$Estimate[length(slope_df$Estimate)]
  )
}
