# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand # nolint: line_length_linter.

#' Get estuary variable from GPS positions
#' 
#' @param data tibble containing columns with GPS position through latitude and longitude columns
#' @param latitude name of latitude column
#' @param longitude name of longitude column
#'
#' @return the tibble + variable estuary
#' 
#' @export
#' @examples
#' toy_data_gps <- data.frame(
#'   station = c(
#'     "GIR_01", "GIR_02", "GIR_03",
#'     "LOI_01", "LOI_02", "LOI_03",
#'     "SEI_01", "SEI_02", "SEI_03"
#'   ),
#'   lat = c(
#'     45.58, 45.52, 45.45,
#'     47.28, 47.30, 47.25,
#'     49.47, 49.45, 49.42
#'   ),
#'   lon = c(
#'     -0.95, -1.05, -1.15,
#'     -2.05, -2.20, -2.35,
#'     0.18, 0.30, 0.42
#'   )
#' )
#'
#' get_estuary_from_gps_position(data = toy_data_gps, latitude = lat, longitude = lon)

get_estuary_from_gps_position <- function(data, latitude, longitude){
  
  completed_data <- data |>
    
    # ---- Add estuary variable ----
  mutate(
    estuary = case_when(
      {{latitude}} >= GPS_limits_estuary[which(GPS_limits_estuary$estuary == "Gironde"), ]$estuary_limit_lat_min &
        {{latitude}} <= GPS_limits_estuary[which(GPS_limits_estuary$estuary == "Gironde"), ]$estuary_limit_lat_max &
        {{longitude}} >= GPS_limits_estuary[which(GPS_limits_estuary$estuary == "Gironde"), ]$estuary_limit_lon_min &
        {{longitude}} <= GPS_limits_estuary[which(GPS_limits_estuary$estuary == "Gironde"), ]$estuary_limit_lon_max ~ "Gironde",
      
      {{latitude}} >= GPS_limits_estuary[which(GPS_limits_estuary$estuary == "Loire"), ]$estuary_limit_lat_min &
        {{latitude}} <= GPS_limits_estuary[which(GPS_limits_estuary$estuary == "Loire"), ]$estuary_limit_lat_max &
        {{longitude}} >= GPS_limits_estuary[which(GPS_limits_estuary$estuary == "Loire"), ]$estuary_limit_lon_min &
        {{longitude}} <= GPS_limits_estuary[which(GPS_limits_estuary$estuary == "Loire"), ]$estuary_limit_lon_max ~ "Loire",
      
      {{latitude}} >= GPS_limits_estuary[which(GPS_limits_estuary$estuary == "Seine"), ]$estuary_limit_lat_min &
        {{latitude}} <= GPS_limits_estuary[which(GPS_limits_estuary$estuary == "Seine"), ]$estuary_limit_lat_max &
        {{longitude}} >= GPS_limits_estuary[which(GPS_limits_estuary$estuary == "Seine"), ]$estuary_limit_lon_min &
        {{longitude}} <= GPS_limits_estuary[which(GPS_limits_estuary$estuary == "Seine"), ]$estuary_limit_lon_max ~ "Seine",
      TRUE ~ NA
    )
  )  |>
    filter(!is.na(estuary))
  
  return(completed_data)
      
}
