# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand # nolint: line_length_linter.

#' Get information from dates
#' 
#' Get year, month, year_month, season, and year_season variables from a date variable
#' 
#' @param data tibble containing a column of class date
#' @param date_variable name of the date column
#'
#' @return the tibble + variables year, month, year_month, season, and year_season
#' 
#' @import dplyr
#' @importFrom lubridate year month
#' 
#' @export
#' @examples
#' # data("economics")
#' # get_info_from_dates(data = economics, date_variable = date)
get_info_from_dates <- function(data, date_variable){
  
    completed_data <- data |> 
      mutate(
        year = lubridate::year({{ date_variable }}),
        month = lubridate::month({{ date_variable }}),
        year_month = paste(year,month, sep = "_"),
        season = lubridate::month({{ date_variable }})
        ) |> 
      mutate(season = case_when(
  month %in% c(12, 1, 2) ~ "winter",
  month %in% c(3,4,5) ~ "spring",
  month %in% c(6,7,8) ~ "summer",
  month %in% c(9,10,11) ~ "autumn"
)) |>
  mutate(year_season = paste(year, season, sep = "_"))
    
    return(completed_data)
}
