# WARNING - Generated by {fusen} from dev/flat_maps.Rmd: do not edit by hand # nolint: line_length_linter.

#' Get mean GPS positions from different points
#' 
#' @return tibble summarised data with mean_latitude and mean_longitude variables
#' 
#' @noRd
get_mean_gps_position <- function(data, latitude, longitude){
  
  data_mean_positions <- data |>
    summarise(
      longitude = mean(longitude, na.rm = TRUE),
      latitude = mean(latitude, na.rm = TRUE)
    )
  
  return(data_mean_positions)
}
