# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand # nolint: line_length_linter.

#' Get haline_zone variable from GPS positions
#' 
#' @param data tibble containing columns with GPS position through latitude and longitude columns
#' @param latitude name of latitude column
#' @param longitude name of longitude column
#'
#' @return the tibble + variable haline_zone
#' 
#' @export
#' @examples
#' toy_data_gps <- data.frame(
#'   estuary = c(
#'     "Gironde", "Gironde", "Gironde",
#'     "Loire", "Loire", "Loire",
#'     "Seine", "Seine", "Seine"
#'   ),
#'   lat = c(
#'     45.58, 45.52, 45.45,
#'     47.28, 47.30, 47.25,
#'     49.47, 49.45, 49.42
#'   ),
#'   lon = c(
#'     -0.95, -1.05, -1.15,
#'     -2.05, -2.20, -2.35,
#'     0.18, 0.30, 0.42
#'   )
#' )
#'
#' get_haline_zone_from_gps_position(data = toy_data_gps, latitude = lat, longitude = lon)

get_haline_zone_from_gps_position <- function(data, latitude, longitude){
  
  data(GPS_limits_haline)
  
  completed_data <- data |>
    
    # ---- Add haline_zone variable ----
  mutate(
    haline_zone = case_when(
      estuary == "Gironde" &
        {{latitude}} >= GPS_limits_haline[which(GPS_limits_haline$estuary == "Gironde"), ]$halin_limit_lat ~ "outer",
      estuary == "Gironde" &
        {{latitude}} < GPS_limits_haline[which(GPS_limits_haline$estuary == "Gironde"), ]$halin_limit_lat ~ "inner",
      estuary == "Loire" &
        {{longitude}} <= GPS_limits_haline[which(GPS_limits_haline$estuary == "Loire"), ]$halin_limit_lon ~ "outer",
      estuary == "Loire" &
        {{longitude}} > GPS_limits_haline[which(GPS_limits_haline$estuary == "Loire"), ]$halin_limit_lon ~ "inner",
      estuary == "Seine" &
        {{longitude}} <= GPS_limits_haline[which(GPS_limits_haline$estuary == "Seine"), ]$halin_limit_lon ~ "outer",
      estuary == "Seine" &
        {{longitude}} > GPS_limits_haline[which(GPS_limits_haline$estuary == "Seine"), ]$halin_limit_lon ~ "inner",
      TRUE ~ NA
    )
  )
  
  return(completed_data)
      
}
