# WARNING - Generated by {fusen} from dev/flat_data_contamination.Rmd: do not edit by hand # nolint: line_length_linter.

#' Get general levels in the original unit of measurment
#' 
#' @param data tibble with ESTUARY, PARAMETRE_LIBELLE, periode, RESULTAT
#' @param family character Family folder name
#' @param suffix character If necessary, a suffix for the output .xlsx file name
#'
#' @return save a .xlsx in the folder "../inst/results/data_contam/"
#' 
#' @import dplyr
#' @import tidyr
#' 
#' @export
#' @examples
#' # get_general_levels()
get_general_levels <- function(data, family, suffix){
  
  data_general_levels_estuary <- data |> 
  drop_na(periode) |> 
  group_by(ESTUARY, PARAMETRE_LIBELLE, periode) |> 
  summarise(median_ng_gww = median(RESULTAT), .groups = "drop") |> 
  arrange(PARAMETRE_LIBELLE) |> 
  pivot_wider(names_from = periode, values_from = median_ng_gww)

data_general_levels <- data |> 
  drop_na(periode) |> 
  group_by(PARAMETRE_LIBELLE, periode) |> 
  summarise(median_ng_gww = median(RESULTAT), .groups = "drop") |> 
  arrange(PARAMETRE_LIBELLE) |> 
  pivot_wider(names_from = periode, values_from = median_ng_gww)

writexl::write_xlsx(x = list(data_general_levels, data_general_levels_estuary), path = paste0("../inst/results/data_contam/", family, "/summarised_levels_data_", family, suffix, ".xlsx"))
}
