# WARNING - Generated by {fusen} from dev/flat_data_contamination.Rmd: do not edit by hand # nolint: line_length_linter.

#' Get results from Spearman's test for several estuaries and contaminant
#' 
#' Last 15 years trend and significance
#' 
#' @param data tibble with ESTUARY, PARAMETRE_LIBELLE, YEAR, RESULTAT
#' @param norm tibble PARAMETRE_LIBELLE, NORM
#'
#' @return tibble ESTUARY, PARAMETRE_LIBELLE, rho, p.value, symbol, last_year, last_resultat, norm
#' 
#' @import dplyr
#' @import tidyr
#' 
#' @export
#' @examples
#' # get_last_trend_info()
get_last_trend_info <- function(data, norm){
  data_last_trend <- data |> 
  filter(last_trend == "Last 15 years")

df_last_info <- data_last_trend |> 
  group_by(ESTUARY, PARAMETRE_LIBELLE) |> 
  summarise(
    last_year = max(YEAR),
    last_resultat = median(RESULTAT[which(YEAR == max(YEAR))]),
    .groups = "drop")

resultats <- data_last_trend  |> 
  group_by(ESTUARY, PARAMETRE_LIBELLE)  |> 
  summarise(
    res = list(spearman_test(x = YEAR, y = RESULTAT)),
    .groups = "drop"
  ) |> 
  unnest(res) |> 
  mutate(symbol = case_when(
    p.value > 0.05 ~ "\u2192",
    rho > 0 ~ "↑",
    rho < 0 ~ "↓",
    TRUE ~ NA
  ))

res_trends <- resultats |> 
  left_join(df_last_info, by = c("ESTUARY", "PARAMETRE_LIBELLE")) |> 
  left_join(norm)
  
return(res_trends)
}
