# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand # nolint: line_length_linter.

#' Interpolation using splinefun(method = "monoH.FC") from
#' 
#' @param data tibble, data with x, y, grouping variable
#' @param x character, x variable
#' @param y character, y variable
#' @param group vector of character, grouping variable
#'
#' @return tibble with interpolated data by group
#' 
#' @noRd
get_interpolation_spline <- function(data, x, y, ...) {
  
  x_var <- rlang::ensym(x)
  y_var <- rlang::ensym(y)
  group_vars <- rlang::ensyms(...)
  
  data |> 
    dplyr::group_by(!!!group_vars) |> 
    dplyr::arrange(!!x_var, .by_group = TRUE) |>
    dplyr::group_modify(~{
      
      x_vals <- dplyr::pull(.x, !!x_var)
      y_vals <- dplyr::pull(.x, !!y_var)
      
      ok <- !is.na(x_vals) & !is.na(y_vals)
      x_vals <- x_vals[ok]
      y_vals <- y_vals[ok]
      
      if (length(x_vals) < 2) {
        return(tibble::tibble(
          !!x_var := x_vals,
          !!y_var := y_vals
        ))
      }
      
      spline_mod <- splinefun(
        x = x_vals,
        y = y_vals,
        method = "monoH.FC"
      )
      
      x_new <- seq(
        min(x_vals),
        max(x_vals),
        by = 1
      )
      
      tibble::tibble(
        !!x_var := x_new,
        !!y_var := spline_mod(x_new)
      )
    }) |> 
    dplyr::ungroup()
}
