# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand # nolint: line_length_linter.

#' Copy an image in a temporary shortened path 
#' Necessary to use knitr::include_graphics for long paths
#' 
#' @return short path to a temp file copy "plot.jpg"
#' 
#' @export
get_shortened_path <- function(complete_path){
  
  img_path <- system.file(complete_path, package = "esteem.overview")
  
  short_path <- tempfile(fileext = ".jpg")
  
  file.copy(img_path, short_path)
  
  return(short_path)
}
