# WARNING - Generated by {fusen} from dev/flat_long_term_trends.Rmd: do not edit by hand # nolint: line_length_linter.

#' Tranform characters separated by "+" in a vector of characters
#' 
#' @return vector of characters
#' 
#' @noRd
get_group_vars_from_grouping <- function(grouping) {
  
  if (is.null(grouping) || is.na(grouping)) {
    return(character(0))
  }
  
  grouping |>
    stringr::str_split("\\s*\\+\\s*") |>
    purrr::pluck(1)
}
