# WARNING - Generated by {fusen} from dev/flat_data_benthos.Rmd: do not edit by hand # nolint: line_length_linter.

#' Get map of REBENT sampling points for each year of monitoring.
#' 
#' @param data tibble data benthos with ESTUARY, YEAR, LIEU_MNEMONIQUE, latitude, longitude
#' @param estuary character "Gironde", "Loire", or "Seine"
#' @param color character color
#'
#' @return ggplot 1 map per year
#' 
#' @import dplyr
#' @import ggplot2
#' @importFrom sf st_as_sf
#' @importFrom sf st_bbox
#' @importFrom sf st_drop_geometry
#' @importFrom sf st_transform
#' @importFrom maptiles get_tiles
#' @importFrom ggspatial layer_spatial
#' 
#' @export
#' @examples
#' # gg_map_parametre_data_benthos()
gg_map_parametre_data_benthos <- function(data, estuaire) {
  
  # Convert to spatial object
  points_sf <- sf::st_as_sf(data, coords = c("longitude", "latitude"), crs = 4326) |>
    filter(ESTUARY == estuaire)
  
  # Define spatial window around points
  # bbox <- sf::st_bbox(points_sf)
  marge <- 0.1
  xlim_gironde <- c(xmin = -1.056 - marge, xmax = -0.7178002414 + marge)
  ylim_gironde <- c(ymin = 45.26208 - marge, ymax = 45.59 + marge)
  xlim_loire <- c(xmin = -2.18166667 - marge, xmax = -1.86466667 + marge)
  ylim_loire <- c(ymin = 47.25321667 - marge, ymax = 47.30533333 + marge)
  xlim_seine <- c(xmin = 0.06607 - marge, xmax = 0.42 + marge)
  ylim_seine <- c(ymin = 49.40612 - marge, ymax = 49.45168 + marge)

  if (estuaire == "Gironde") {
    xlim <- xlim_gironde
    ylim <- ylim_gironde
  } else{
    if (estuaire == "Loire") {
      xlim <- xlim_loire
      ylim <- ylim_loire
    } else{
      if (estuaire == "Seine") {
        xlim <- xlim_seine
        ylim <- ylim_seine
      } else{
        print("Unknown estuary")
      }
    }
  }
  
  
  bbox_sf <- sf::st_as_sfc(st_bbox(
    c(xmin = xlim[["xmin"]], ymin = ylim[["ymin"]], 
      xmax = xlim[["xmax"]], ymax = ylim[["ymax"]]),
    crs = 4326))
    
  # Load IGN map tiles
  tiles <- maptiles::get_tiles(x = bbox_sf, provider = "Esri.WorldImagery", crop = TRUE, zoom = 13)

  # Create a table with annotations: number of points per year
  annot_df <- points_sf |>
    sf::st_drop_geometry() |>
    group_by(YEAR) |>
    summarise(n = n()) |>
    mutate(
      label = paste("n =", n),
      longitude = xlim["xmin"] + 0.01,  # Fix position
      latitude = ylim["ymax"] - 0.01
    )
  
  # Plot
  plot <- ggplot() +
    ggspatial::layer_spatial(tiles) +
    geom_sf(data = sf::st_transform(points_sf, 3857), size = 1, 
            aes(color = zone, shape = tidal)) +
    geom_text(data = annot_df, aes(x = longitude, y = latitude, label = label), 
              inherit.aes = FALSE, hjust = 0, vjust = 1, size = 4, fontface = "bold", color = "white") +
    coord_sf(xlim = xlim, ylim = ylim, expand = FALSE) +
    facet_wrap(vars(YEAR)) +
    labs(title = estuaire) +
    theme_minimal() +
    theme(legend.position = "none")  
  
  return(plot)
}
