# WARNING - Generated by {fusen} from dev/flat_data_contamination.Rmd: do not edit by hand # nolint: line_length_linter.

#' Get map of ROCCHMV sampling points with number of years of monitoring.
#' 
#' @param data tibble with ESTUARY, YEAR, LIEU_MNEMONIQUE, latitude, longitude
#' @param estuary character "Gironde", "Loire", or "Seine"
#' @param color character color
#' 
#' @return ggplot map
#'
#' @return ggplot
#' @import dplyr
#' @import ggplot2
#' @importFrom sf st_as_sf
#' @importFrom sf st_bbox
#' @importFrom sf st_drop_geometry
#' 
#' @export
#' @examples
#' # gg_map_data_contamination_rocchmv()
gg_map_data_contamination_rocchmv <- function(data, estuary, color) {
  
  data <- data |>
   count(ESTUARY, YEAR, LIEU_MNEMONIQUE, latitude, longitude)
  
  data_summarized <- data |>
    count(ESTUARY, LIEU_MNEMONIQUE, latitude, longitude)
  
  # Convert to spatial object
  points_sf <- st_as_sf(data_summarized,
                        coords = c("longitude", "latitude"),
                        crs = 4326) |>
    filter(ESTUARY == estuary)
  
  # Define spatial window around points
  bbox <- st_bbox(points_sf)
  marge <- 0.1
  xlim <- c(bbox["xmin"] - marge, bbox["xmax"] + marge)
  ylim <- c(bbox["ymin"] - marge, bbox["ymax"] + marge)
  
  # Plot
  ggplot() +
    geom_sf(data = esteem.overview::fr_map, fill = "grey95", color = "grey50") +
    geom_sf(data = points_sf, size = 1, color = color) +
    geom_text(
      data = data_summarized,
      aes(x = longitude, y = latitude, label = n),
      inherit.aes = FALSE,
      hjust = 0, vjust = 2, size = 4, fontface = "bold"
    ) +
    coord_sf(xlim = xlim, ylim = ylim, expand = FALSE) +
    labs(title = paste0(estuary, " estuary")) +
    theme_minimal()
}
