# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand # nolint: line_length_linter.

#' ggplot2 colors
#' 
#' Reproduce a vector of colors like those from {ggplot2}
#' 
#' @param n number of colors needed
#'
#' @return vector of hexadecimal colors
#' 
#' @export
#' @examples
#' ggplot2_colors(1)
ggplot2_colors <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}
