# WARNING - Generated by {fusen} from dev/flat_fct_build_and_save_basemap.Rmd: do not edit by hand # nolint: line_length_linter.

#' Load estuary basemap (OpenStreetMap)
#' 
#' @param estuary_name Character name of estuary
#' @param package Name of package (default = "esteem.overview")
#'
#' @return List containing osm_raster, villes, xlim, ylim
#' 
#' @export
#' @examples
#' basemap <- load_estuary_basemap(estuary_name = "Loire" )
#' # 
#' # ggplot() +
#' #   tidyterra::geom_spatraster_rgb(data = basemap$osm_raster) +
#' #   geom_sf(data = basemap$villes) +
#' #   coord_sf(xlim = basemap$xlim,
#' #            ylim = basemap$ylim,
#' #            expand = FALSE)
load_estuary_basemap <- function(estuary_name,
                                 package = "esteem.overview") {

  base_path <- system.file("extdata",
                           estuary_name,
                           package = package)

  if (base_path == "") {
    stop("Estuary not found in package extdata/")
  }

  # Raster
  osm_raster_path <- file.path(base_path, "osm.tif")

  if (!file.exists(osm_raster_path)) {
    stop("osm.tif not found for this estuary.")
  }

  osm_raster <- terra::rast(osm_raster_path)

  # Cities
  villes_path <- file.path(base_path, "villes.gpkg")

  if (file.exists(villes_path)) {
    villes <- sf::st_read(villes_path, quiet = TRUE)
  } else {
    villes <- NULL
  }

  # Bbox
  bbox_path <- file.path(base_path, "bbox.rds")

  if (!file.exists(bbox_path)) {
    stop("bbox.rds not found for this estuary.")
  }

  bbox <- readRDS(bbox_path)

  return(list(
    osm_raster = osm_raster,
    villes = villes,
    xlim = bbox$xlim,
    ylim = bbox$ylim,
    halin_limit_lat = bbox$halin_limit_lat,
    halin_limit_lon = bbox$halin_limit_lon
  ))
}
