# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand # nolint: line_length_linter.

#' Make points_sf from "pos_long_dd" & "pos_lat_dd" in a dataset
#' 
#' @noRd
make_points_sf <- function(data) {
  data |>
    dplyr::filter(!is.na(pos_lat_dd) & !is.na(pos_long_dd)) |>
    sf::st_as_sf(
      coords = c("pos_long_dd", "pos_lat_dd"),
      crs = 4326,
      remove = FALSE
    )
}
