# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand # nolint: line_length_linter.

#' Make points_sf from "longitude" & "latitude" in a dataset
#' 
#' @noRd
make_points_sf <- function(data) {
  data |>
    dplyr::filter(!is.na(latitude) & !is.na(longitude)) |>
    sf::st_as_sf(
      coords = c("longitude", "latitude"),
      crs = 4326,
      remove = FALSE
    )
}
