# WARNING - Generated by {fusen} from dev/flat_maps.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot estuary map with points, optional variable mapping and optional fixed aesthetics
#'
#' @param data Data frame containing latitude and longitude.
#' @param estuary_name Character name of the estuary.
#' @param colour_var Optional variable in `data`, or fixed colour value, for point outline colour.
#' @param colour_points Fixed point outline colour used when `colour_var` is not supplied.
#' @param fill_var Optional variable in `data`, or fixed colour value, for point fill.
#' @param fill_points Fixed point fill colour used when `fill_var` is not supplied.
#' @param size_var Optional variable in `data`, or fixed numeric value, for point size.
#' @param size_points Fixed point size used when `size_var` is not supplied.
#' @param shape_var Optional variable in `data`, or fixed shape value, for point shape.
#' @param shape_points Fixed point shape used when `shape_var` is not supplied.
#' @param package Package name where basemap is stored.
#'
#' @return ggplot object.
#' @export
plot_estuary_map <- function(data,
                             estuary_name,
                             colour_var,
                             colour_points = "black",
                             fill_var,
                             fill_points = NA,
                             size_var,
                             size_points = 0.6,
                             shape_var,
                             shape_points = 19,
                             package = "esteem.overview") {

  # ---------------------------------------------------------
  # Helper: check whether an input is a valid colour value
  # ---------------------------------------------------------

  is_colour_value <- function(x) {
    is.character(x) &&
      length(x) == 1 &&
      (
        grepl("^#(?:[0-9A-Fa-f]{3}){1,2}$", x) ||
          x %in% grDevices::colors()
      )
  }

  # ---------------------------------------------------------
  # Helper: resolve variable mapping or fixed aesthetic value
  # ---------------------------------------------------------

  resolve_aesthetic <- function(var,
                                data,
                                type = c("colour", "fill", "size", "shape")) {
    type <- match.arg(type)

    quo <- rlang::enquo(var)
    expr <- rlang::get_expr(quo)

    # If the argument is an unquoted column name present in data,
    # treat it as a mapped aesthetic.
    if (rlang::is_symbol(expr)) {
      var_name <- rlang::as_string(expr)

      if (var_name %in% names(data)) {
        return(list(mapping = quo, value = NULL))
      }
    }

    # Otherwise, try to evaluate the argument as a fixed value.
    val <- tryCatch(
      rlang::eval_tidy(quo),
      error = function(e) NULL
    )

    is_fixed_value <- switch(
      type,
      colour = is_colour_value(val),
      fill   = is_colour_value(val) || (length(val) == 1 && is.na(val)),
      size   = is.numeric(val) && length(val) == 1,
      shape  = (is.numeric(val) || is.character(val)) && length(val) == 1
    )

    if (is_fixed_value) {
      list(mapping = NULL, value = val)
    } else {
      list(mapping = quo, value = NULL)
    }
  }

  # ---------------------------------------------------------
  # Load estuary basemap
  # ---------------------------------------------------------

  basemap <- load_estuary_basemap(
    estuary_name,
    package = package
  )

  # ---------------------------------------------------------
  # Convert sampling data to sf points
  # ---------------------------------------------------------

  points_sf <- make_points_sf(data)

  # Keep points in WGS84 for consistency with the OSM raster.
  points_sf <- sf::st_transform(points_sf, 4326)

  points_coords <- cbind(
    sf::st_drop_geometry(points_sf),
    sf::st_coordinates(points_sf)
  )

  # ---------------------------------------------------------
  # Prepare city locations
  # ---------------------------------------------------------

  if (!is.null(basemap$villes) && nrow(basemap$villes) > 0) {
    basemap$villes <- sf::st_transform(
      basemap$villes,
      4326
    )
  }

  # ---------------------------------------------------------
  # Convert raster basemap to dataframe for ggplot
  # ---------------------------------------------------------

  raster_df <- terra::as.data.frame(
    basemap$osm_raster,
    xy = TRUE,
    na.rm = FALSE
  )

  rgb_cols <- setdiff(
    names(raster_df),
    c("x", "y")
  )[1:3]

  raster_df$rgb <- grDevices::rgb(
    raster_df[[rgb_cols[1]]],
    raster_df[[rgb_cols[2]]],
    raster_df[[rgb_cols[3]]],
    maxColorValue = 255
  )

  # ---------------------------------------------------------
  # Initialise base map
  # ---------------------------------------------------------

  p <- ggplot2::ggplot() +
    ggplot2::geom_raster(
      data = raster_df,
      ggplot2::aes(
        x = x,
        y = y,
        fill = rgb
      )
    ) +
    ggplot2::scale_fill_identity()

  # ---------------------------------------------------------
  # Initialise point aesthetic defaults
  # ---------------------------------------------------------

  mapping <- list()

  point_colour <- colour_points
  point_fill   <- fill_points
  point_size   <- size_points
  point_shape  <- shape_points

  # ---------------------------------------------------------
  # Resolve point colour aesthetic
  # ---------------------------------------------------------

  if (!missing(colour_var)) {
    colour_res <- resolve_aesthetic(
      {{ colour_var }},
      points_coords,
      type = "colour"
    )

    if (!is.null(colour_res$mapping)) {
      mapping$colour <- colour_res$mapping
      point_colour <- NULL
    } else {
      point_colour <- colour_res$value
    }
  }

  # ---------------------------------------------------------
  # Resolve point fill aesthetic
  # ---------------------------------------------------------

  if (!missing(fill_var)) {
    fill_res <- resolve_aesthetic(
      {{ fill_var }},
      points_coords,
      type = "fill"
    )

    if (!is.null(fill_res$mapping)) {
      mapping$fill <- fill_res$mapping
      point_fill <- NULL
    } else {
      point_fill <- fill_res$value
    }
  }

  # ---------------------------------------------------------
  # Resolve point size aesthetic
  # ---------------------------------------------------------

  if (!missing(size_var)) {
    size_res <- resolve_aesthetic(
      {{ size_var }},
      points_coords,
      type = "size"
    )

    if (!is.null(size_res$mapping)) {
      mapping$size <- size_res$mapping
      point_size <- NULL
    } else {
      point_size <- size_res$value
    }
  }

  # ---------------------------------------------------------
  # Resolve point shape aesthetic
  # ---------------------------------------------------------

  if (!missing(shape_var)) {
    shape_res <- resolve_aesthetic(
      {{ shape_var }},
      points_coords,
      type = "shape"
    )

    if (!is.null(shape_res$mapping)) {
      mapping$shape <- shape_res$mapping
      point_shape <- NULL
    } else {
      point_shape <- shape_res$value
    }
  }

  # ---------------------------------------------------------
  # Select a fill-compatible default shape when fill is mapped
  # ---------------------------------------------------------

  if (!"shape" %in% names(mapping) && "fill" %in% names(mapping)) {
    point_shape <- 21
  }

  # ---------------------------------------------------------
  # Build point aesthetic mapping
  # ---------------------------------------------------------

  point_mapping <- c(
    list(
      x = quote(X),
      y = quote(Y)
    ),
    mapping
  )

  # ---------------------------------------------------------
  # Build geom_point() arguments
  # ---------------------------------------------------------

  point_args <- list(
    data = points_coords,
    mapping = do.call(ggplot2::aes, point_mapping),
    alpha = 0.8
  )

  if (!is.null(point_colour)) {
    point_args$colour <- point_colour
  }

  if (!is.null(point_fill)) {
    point_args$fill <- point_fill
  }

  if (!is.null(point_size)) {
    point_args$size <- point_size
  }

  if (!is.null(point_shape)) {
    point_args$shape <- point_shape
  }

  # ---------------------------------------------------------
  # Add sampling points
  # ---------------------------------------------------------

  p <- p + do.call(ggplot2::geom_point, point_args)

  # ---------------------------------------------------------
  # Add cities and city labels
  # ---------------------------------------------------------

  if (!is.null(basemap$villes) && nrow(basemap$villes) > 0) {
    villes_coords <- cbind(
      sf::st_drop_geometry(basemap$villes),
      sf::st_coordinates(basemap$villes)
    )

    p <- p +
      ggplot2::geom_point(
        data = villes_coords,
        ggplot2::aes(
          x = X,
          y = Y
        ),
        shape = 21,
        fill = "black",
        colour = "black",
        size = 1.5
      ) +
      ggrepel::geom_text_repel(
        data = villes_coords,
        ggplot2::aes(
          x = X,
          y = Y,
          label = name
        ),
        min.segment.length = 0,
        nudge_y = 0.01,
        size = 2.3,
        colour = "black",
        family = "sans"
      )
  }

  # ---------------------------------------------------------
  # Prepare salinity limit coordinates
  # ---------------------------------------------------------

  line_frac <- 0.45

  x_mid <- mean(basemap$xlim)
  y_mid <- mean(basemap$ylim)

  x_half <- diff(basemap$xlim) * line_frac / 2
  y_half <- diff(basemap$ylim) * line_frac / 2

  # ---------------------------------------------------------
  # Add horizontal salinity limit when available
  # ---------------------------------------------------------

  if (!is.null(basemap$halin_limit_lat) &&
      !is.na(basemap$halin_limit_lat)) {
    line_data <- data.frame(
      x = x_mid - x_half,
      xend = x_mid + x_half,
      y = basemap$halin_limit_lat,
      yend = basemap$halin_limit_lat
    )

    p <- p +
      ggplot2::geom_segment(
        data = line_data,
        ggplot2::aes(
          x = x,
          xend = xend,
          y = y,
          yend = yend
        ),
        colour = "black",
        linewidth = 0.8
      )
  }

  # ---------------------------------------------------------
  # Add vertical salinity limit when available
  # ---------------------------------------------------------

  if (!is.null(basemap$halin_limit_lon) &&
      !is.na(basemap$halin_limit_lon)) {
    line_data <- data.frame(
      x = basemap$halin_limit_lon,
      xend = basemap$halin_limit_lon,
      y = y_mid - y_half,
      yend = y_mid + y_half
    )

    p <- p +
      ggplot2::geom_segment(
        data = line_data,
        ggplot2::aes(
          x = x,
          xend = xend,
          y = y,
          yend = yend
        ),
        colour = "black",
        linewidth = 0.8
      )
  }

  # ---------------------------------------------------------
  # Set map extent
  # ---------------------------------------------------------

  raster_xlim <- range(raster_df$x, na.rm = TRUE)
  raster_ylim <- range(raster_df$y, na.rm = TRUE)

  p <- p +
    ggplot2::coord_cartesian(
      xlim = raster_xlim,
      ylim = raster_ylim,
      expand = FALSE
    )

  # ---------------------------------------------------------
  # Apply theme and axis formatting
  # ---------------------------------------------------------

  p <- p +
    theme_esteem() +
    ggplot2::theme(
      plot.title = ggplot2::element_text(size = 9),
      axis.title = ggplot2::element_blank(),
      axis.text = ggplot2::element_text(size = 6)
    ) +
    ggplot2::scale_x_continuous(
      labels = scales::label_number(accuracy = 0.01)
    ) +
    ggplot2::scale_y_continuous(
      labels = scales::label_number(accuracy = 0.01)
    )

  # ---------------------------------------------------------
  # Add plot title
  # ---------------------------------------------------------

  p <- p +
    ggplot2::labs(
      title = paste0(estuary_name, " estuary")
    )

  # ---------------------------------------------------------
  # Return final plot
  # ---------------------------------------------------------

  return(p)
}

