# WARNING - Generated by {fusen} from dev/flat_maps.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot estuary map with points, optional variable mapping and optional horizontal/vertical lines
#'
#' @param data Data frame containing latitude and longitude
#' @param estuary_name Character name of the estuary
#' @param colour_var Optional variable in `data` for point colour
#' @param fill_var Optional variable in `data` for point fill (shape 21)
#' @param size_var Optional variable in `data` for point size
#' @param shape_var Optional variable in `data` for point shape
#' @param package Package name where basemap is stored (default: "esteem.overview")
#'
#'
#' @import dplyr
#' @import ggplot2
#' @importFrom ggrepel geom_text_repel
#' @importFrom rlang ensym
#' @importFrom rlang sym
#' @importFrom sf st_as_sf
#' @importFrom sf st_coordinates
#' @importFrom rlang enquo quo_is_null
#' 
#' @return ggplot object
#' @export
plot_estuary_map <- function(data,
                             estuary_name,
                             colour_var,
                             fill_var,
                             size_var,
                             size_points = 0.6,
                             shape_var,
                             package = "esteem.overview") {

  # -------------------------
  # 1. Load basemap
  # -------------------------
  basemap <- load_estuary_basemap(
    estuary_name,
    package = package
  )

  # -------------------------
  # 2. Convert data to sf
  # -------------------------
  points_sf <- make_points_sf(data)

  # IMPORTANT :
  # rester en WGS84 pour cohérence avec raster OSM
  points_sf <- sf::st_transform(points_sf, 4326)

  points_coords <- cbind(
  sf::st_drop_geometry(points_sf),
  sf::st_coordinates(points_sf)
)
  
  if (!is.null(basemap$villes) &&
      nrow(basemap$villes) > 0) {

    basemap$villes <- sf::st_transform(
      basemap$villes,
      4326
    )
  }

  # -------------------------
  # 3. Convert raster to dataframe
  #    pour éviter coord_sf()
  # -------------------------
  raster_df <- terra::as.data.frame(
    basemap$osm_raster,
    xy = TRUE,
    na.rm = FALSE
  )

  rgb_cols <- setdiff(
    names(raster_df),
    c("x", "y")
  )[1:3]

  raster_df$rgb <- grDevices::rgb(
    raster_df[[rgb_cols[1]]],
    raster_df[[rgb_cols[2]]],
    raster_df[[rgb_cols[3]]],
    maxColorValue = 255
  )

  # -------------------------
  # 4. Base plot
  # -------------------------
  p <- ggplot2::ggplot() +

    ggplot2::geom_raster(
      data = raster_df,
      ggplot2::aes(
        x = x,
        y = y,
        fill = rgb
      )
    ) +

    ggplot2::scale_fill_identity()

  
  # -------------------------
  # 5. Dynamic aesthetic mapping
  # -------------------------
  
  mapping <- list()

  if (!missing(colour_var)) {
    mapping$colour <- rlang::enquo(colour_var)
  }

  if (!missing(fill_var)) {
    mapping$fill <- rlang::enquo(fill_var)
  }

  if (!missing(size_var)) {
    mapping$size <- rlang::enquo(size_var)
  }

  if (!missing(shape_var)) {
    mapping$shape <- rlang::enquo(shape_var)
  }

  if (length(mapping) > 0) {

  geom_shape <- NULL

  if (!"shape" %in% names(mapping)) {

    if ("fill" %in% names(mapping)) {
      geom_shape <- 21
    } else {
      geom_shape <- 19
    }
  }

  point_mapping <- c(
    list(
      x = quote(X),
      y = quote(Y)
    ),
    mapping
  )

  if (is.null(geom_shape)) {

    p <- p +
      ggplot2::geom_point(
        data = points_coords,
        mapping = do.call(
          ggplot2::aes,
          point_mapping
        ),
        alpha = 0.8,
        size = size_points
      )

  } else {

    p <- p +
      ggplot2::geom_point(
        data = points_coords,
        mapping = do.call(
          ggplot2::aes,
          point_mapping
        ),
        shape = geom_shape,
        alpha = 0.8,
        size = size_points,
      )
  }

} else {

  p <- p +
    ggplot2::geom_point(
      data = points_coords,
      ggplot2::aes(
        x = X,
        y = Y
      ),
      size = size_points,
      alpha = 0.8
    )
}
  
  # -------------------------
  # 6. Cities + labels
  # -------------------------
  
  if (!is.null(basemap$villes) &&
      nrow(basemap$villes) > 0) {

    villes_coords <- cbind(
      sf::st_drop_geometry(basemap$villes),
      sf::st_coordinates(basemap$villes)
    )

    p <- p +
      ggplot2::geom_point(
        data = villes_coords,
        ggplot2::aes(
          x = X,
          y = Y
        ),
        shape = 21,
        fill = "black",
        color = "black",
        size = 1.5
      ) +
      ggrepel::geom_text_repel(
        data = villes_coords,
        ggplot2::aes(
          x = X,
          y = Y,
          label = name
        ),
        min.segment.length = 0,
        nudge_y = 0.01,
        size = 2.3,
        color = "black",
        family = "sans"
      )
  }

 # -------------------------
  # 7. Limite haline
  # -------------------------

  line_frac <- 0.45

  x_mid  <- mean(basemap$xlim)
  y_mid  <- mean(basemap$ylim)

  x_half <- diff(basemap$xlim) *
    line_frac / 2

  y_half <- diff(basemap$ylim) *
    line_frac / 2

  # ---- Ligne horizontale
  if (!is.null(basemap$halin_limit_lat) &&
      !is.na(basemap$halin_limit_lat)) {

    line_data <- data.frame(
      x    = x_mid - x_half,
      xend = x_mid + x_half,
      y    = basemap$halin_limit_lat,
      yend = basemap$halin_limit_lat
    )

    p <- p +
      ggplot2::geom_segment(
        data = line_data,
        ggplot2::aes(
          x = x,
          xend = xend,
          y = y,
          yend = yend
        ),
        color = "black",
        linewidth = 0.8
      )
  }

  # ---- Ligne verticale
  
  if (!is.null(basemap$halin_limit_lon) &&
      !is.na(basemap$halin_limit_lon)) {

    line_data <- data.frame(
      x    = basemap$halin_limit_lon,
      xend = basemap$halin_limit_lon,
      y    = y_mid - y_half,
      yend = y_mid + y_half
    )

    p <- p +
      ggplot2::geom_segment(
        data = line_data,
        ggplot2::aes(
          x = x,
          xend = xend,
          y = y,
          yend = yend
        ),
        color = "black",
        linewidth = 0.8
      )
  }
  
  # -------------------------
  # 8. Coordinates
  # -------------------------

  raster_xlim <- range(raster_df$x, na.rm = TRUE)
  raster_ylim <- range(raster_df$y, na.rm = TRUE)

  p <- p +
    ggplot2::coord_cartesian(
      xlim = raster_xlim,
      ylim = raster_ylim,
      expand = FALSE
    ) +
    theme_esteem() +
    ggplot2::theme(
      plot.title = ggplot2::element_text(size = 9),
  axis.title = ggplot2::element_blank(),
  axis.text = ggplot2::element_text(size = 6)
    ) +
  # 2 decimals for GPS values
    ggplot2::scale_x_continuous(labels = scales::label_number(accuracy = 0.01)) +
    ggplot2::scale_y_continuous(labels = scales::label_number(accuracy = 0.01))

  # -------------------------
  # 9. Title
  # -------------------------
  
  p <- p +
    ggplot2::labs(title = paste0(estuary_name, " estuary"))
  
  # -------------------------
  # 10. Final map
  # -------------------------
  
  return(p)
}
