# WARNING - Generated by {fusen} from dev/flat_long_term_trends.Rmd: do not edit by hand # nolint: line_length_linter.

#' Automate graph function for time-series across all parameters
#' 
#' Description
#' 
#' @return list of ggplots
#' 
#' @export
plot_trends_by_parameter <- function(data,
                                     gam_results,
                                     response_col = "RESULTAT",
                                     x_col = "year_month",
                                     parameter_col = "PARAMETRE_LIBELLE",
                                     grouping = NULL,
                                     colour_var = NULL,
                                     facet_rows = NULL,
                                     facet_cols = NULL,
                                     auto_layout = TRUE,
                                     ...) {
  
  # Déduction automatique du grouping si un seul existe dans gam_results
  if (is.null(grouping) && "grouping" %in% names(gam_results)) {
    
    unique_grouping <- unique(gam_results$grouping)
    unique_grouping <- unique_grouping[!is.na(unique_grouping)]
    
    if (length(unique_grouping) == 1) {
      grouping <- unique_grouping
    }
  }
  
  parameters <- data |>
    distinct(.data[[parameter_col]]) |>
    arrange(.data[[parameter_col]]) |>
    pull(.data[[parameter_col]])
  
  plots <- parameters |>
    set_names() |>
    map(
      ~ plot_trend_one_parameter(
        data = data,
        gam_results = gam_results,
        parameter_value = .x,
        response_col = response_col,
        x_col = x_col,
        parameter_col = parameter_col,
        grouping = grouping,
        colour_var = colour_var,
        facet_rows = facet_rows,
        facet_cols = facet_cols,
        auto_layout = auto_layout,
        ...
      )
    )
  
  plots
}
