# WARNING - Generated by {fusen} from dev/flat_long_term_trends.Rmd: do not edit by hand # nolint: line_length_linter.

#' Graph function for time-series of one parameter
#' 
#' Description
#' 
#' @return ggplot
#' 
#' @noRd
plot_trend_one_parameter <- function(data,
                                     gam_results,
                                     parameter_value,
                                     response_col = "RESULTAT",
                                     x_col = "year_month",
                                     parameter_col = "PARAMETRE_LIBELLE",
                                     grouping = NULL,
                                     colour_var = NULL,
                                     facet_rows = NULL,
                                     facet_cols = NULL,
                                     auto_layout = TRUE,
                                     point_alpha = 0.5,
                                     point_size = 1,
                                     smooth = TRUE,
                                     smooth_method = "gam",
                                     smooth_formula = y ~ s(x, k = 6),
                                     symbol_linear = "▲",
                                     symbol_nonlinear = "●",
                                     symbol_size = 5) {
  
  # Sécurité alpha
  point_alpha <- as.numeric(point_alpha)[1]
  if (is.na(point_alpha)) point_alpha <- 0.5
  
  # Si grouping non fourni, on essaie de le déduire automatiquement
  if (is.null(grouping) && "grouping" %in% names(gam_results)) {
    unique_grouping <- unique(gam_results$grouping)
    unique_grouping <- unique_grouping[!is.na(unique_grouping)]
    
    if (length(unique_grouping) == 1) {
      grouping <- unique_grouping
    }
  }
  
  group_vars <- get_group_vars_from_grouping(grouping)
  
  if (auto_layout && length(group_vars) > 0) {
    
    layout <- auto_plot_layout(group_vars)
    
    if (is.null(colour_var)) {
      colour_var <- layout$colour_var
    }
    
    if (is.null(facet_rows)) {
      facet_rows <- layout$facet_rows
    }
    
    if (is.null(facet_cols)) {
      facet_cols <- layout$facet_cols
    }
  }
  
  join_vars <- c(parameter_col, group_vars)
  
  data_param <- data |>
    filter(.data[[parameter_col]] == parameter_value) |>
    filter(!is.na(.data[[response_col]]), !is.na(.data[[x_col]]))
  
  if (nrow(data_param) == 0) {
    warning("Aucune donnée pour le paramètre : ", parameter_value)
    return(NULL)
  }
  
  gam_param <- gam_results |>
    filter(.data[[parameter_col]] == parameter_value)
  
  if (!is.null(grouping) && "grouping" %in% names(gam_param)) {
    gam_param <- gam_param |>
      filter(.data[["grouping"]] == grouping)
  }
  
  gam_symbols <- gam_param |>
    mutate(
      trend_symbol = case_when(
        stringr::str_detect(
          trend_type,
          stringr::regex("non-linear", ignore_case = TRUE)
        ) &
          !stringr::str_detect(
            trend_type,
            stringr::regex("no significant", ignore_case = TRUE)
          ) ~ symbol_nonlinear,
        
        stringr::str_detect(
          trend_type,
          stringr::regex("linear|monotonic", ignore_case = TRUE)
        ) &
          !stringr::str_detect(
            trend_type,
            stringr::regex("no significant", ignore_case = TRUE)
          ) ~ symbol_linear,
        
        TRUE ~ NA_character_
      )
    ) |>
    filter(!is.na(trend_symbol))
  
  # Dernier point observé de chaque série
  if (length(group_vars) > 0) {
    
    last_points <- data_param |>
      group_by(across(all_of(group_vars))) |>
      arrange(.data[[x_col]], .by_group = TRUE) |>
      slice_tail(n = 1) |>
      ungroup()
    
  } else {
    
    last_points <- data_param |>
      arrange(.data[[x_col]]) |>
      slice_tail(n = 1)
  }
  
  # Jointure avec les résultats GAM
  if (length(group_vars) > 0 && all(join_vars %in% names(gam_symbols))) {
    
    last_points <- last_points |>
      left_join(
        gam_symbols |>
          select(all_of(join_vars), trend_type, trend_symbol),
        by = join_vars
      ) |>
      filter(!is.na(trend_symbol))
    
  } else if (nrow(gam_symbols) > 0) {
    
    last_points <- last_points |>
      mutate(
        trend_type = gam_symbols$trend_type[1],
        trend_symbol = gam_symbols$trend_symbol[1]
      ) |>
      filter(!is.na(trend_symbol))
    
  } else {
    
    last_points <- last_points |>
      mutate(
        trend_type = NA_character_,
        trend_symbol = NA_character_
      ) |>
      filter(!is.na(trend_symbol))
  }
  
  # ------------------------------------------------------------------
  # ggplot robuste
  # ------------------------------------------------------------------
  
  if (is.null(colour_var)) {
    
    p <- ggplot(
      data_param,
      aes(
        x = .data[[x_col]],
        y = .data[[response_col]]
      )
    )
    
  } else {
    
    p <- ggplot(
      data_param,
      aes(
        x = .data[[x_col]],
        y = .data[[response_col]],
        colour = .data[[colour_var]]
      )
    )
  }
  
  p <- p +
    geom_point(
      alpha = point_alpha,
      size = point_size
    )
  
  if (smooth) {
    p <- p +
      geom_smooth(
        method = smooth_method,
        formula = smooth_formula,
        se = TRUE
      )
  }
  
  # Symboles de tendance
  if (nrow(last_points) > 0) {
    
    if (is.null(colour_var)) {
      
      p <- p +
        geom_text(
          data = last_points,
          aes(
            x = .data[[x_col]],
            y = .data[[response_col]],
            label = trend_symbol
          ),
          size = symbol_size,
          vjust = -0.8,
          show.legend = FALSE
        )
      
    } else {
      
      p <- p +
        geom_text(
          data = last_points,
          aes(
            x = .data[[x_col]],
            y = .data[[response_col]],
            label = trend_symbol,
            colour = .data[[colour_var]]
          ),
          size = symbol_size,
          vjust = -0.8,
          show.legend = FALSE
        )
    }
  }
    
  # Facettes
  if (!is.null(facet_rows) || !is.null(facet_cols)) {
    
    rows <- if (!is.null(facet_rows)) vars(!!sym(facet_rows)) else vars()
    cols <- if (!is.null(facet_cols)) vars(!!sym(facet_cols)) else vars()
    
    p <- p +
      facet_grid(
        rows = rows,
        cols = cols,
        scales = "free_y"
      )
  }
  
  p +
    labs(
      title = parameter_value,
      x = x_col,
      y = response_col,
      colour = colour_var
    ) +
    theme_bw() +
    theme(
      strip.background = element_rect(fill = "grey95"),
      panel.grid.minor = element_blank()
    )
}
