# WARNING - Generated by {fusen} from dev/flat_maps.Rmd: do not edit by hand # nolint: line_length_linter.

#' Map yearly mean GPS position by estuary and haline zone
#' 
#' @param data tibble, data containing PARAMETRE_LIBELLE, estuary, year, haline_zone, latitude, longitude
#' @param parameter character, name of the parameter GPS measurment positions to be mapped
#' @param filename character, complete path where to save the map
#'
#' @return saved ggplot
#' 
#' @export
plot_maps_parameter_years <- function(data, parameter, filename){
  
  map_mean_positions <- data |>
    filter(PARAMETRE_LIBELLE == parameter) |>
    drop_na(RESULTAT) |> 
    group_by(estuary, year, haline_zone) |>
    get_mean_gps_position()

p1 <- plot_estuary_map(data = map_mean_positions,
                 estuary_name = "Gironde", 
                 colour_var = year, size_points = 2) +
  scale_colour_viridis_c(option = "plasma", end = 0.95)

p2 <- plot_estuary_map(data = map_mean_positions,
                 estuary_name = "Loire", 
                 colour_var = year, size_points = 2) +
  scale_colour_viridis_c(option = "plasma", end = 0.95)

p3 <- plot_estuary_map(data = map_mean_positions,
                 estuary_name = "Seine", 
                 colour_var = year,  size_points = 2) +
  scale_colour_viridis_c(option = "plasma", end = 0.95)

ggplot_parameter_map <- plot_grid(p1, p2, p3, ncol = 1)


ggsave(plot = ggplot_parameter_map,
       filename = filename,
       height = 20, width = 15, units = "cm")
}
