# WARNING - Generated by {fusen} from dev/flat_phychem.Rmd: do not edit by hand # nolint: line_length_linter.

#' Get ggplot of a physico-chemical parameter time series and trends
#' 
#' @param data tibble with year_month, PARAMETRE_LIBELLE, RESULTAT, season, estuary, and haline zone variables
#' @param parameter character, name of the parameter to be plotted
#' @param threshold numeric or NULL, horizontal threshold
#' @param ylab character, y axis title
#'
#' @return ggplot of parameter time series and trends
#' 
#' @noRd
plot_physicochem_parameter_trend <- function(data, 
                                             parameter, 
                                             threshold, 
                                             ylab) {
  filtered_data <- data |>
    filter(PARAMETRE_LIBELLE == {{parameter}})
  
  plot <- ggplot(filtered_data) +
    aes(x = year_month, y = RESULTAT, colour = season) +
    geom_line() +
    geom_hline(yintercept = threshold) +
    geom_smooth() +
    labs(y = ylab) +
    theme(axis.title.x = element_blank()) +
    facet_grid(rows = vars(estuary), cols = vars(haline_zone))

  return(plot)
}
