# WARNING - Generated by {fusen} from dev/flat_maps.Rmd: do not edit by hand # nolint: line_length_linter.

#' Title
#' 
#' Description
#' 
#' @param x 
#' @param angle 
#' @param center 
#'
#' @return
#' @noRd
rotate_sf <- function(x, angle_deg, center) {
  
  if (is.null(x) || nrow(x) == 0 || angle_deg == 0) {
    return(x)
  }
  
  crs_x <- sf::st_crs(x)
  
  angle_rad <- angle_deg * pi / 180
  
  rot_matrix <- matrix(
    c(
      cos(angle_rad), -sin(angle_rad),
      sin(angle_rad),  cos(angle_rad)
    ),
    nrow = 2,
    byrow = TRUE
  )
  
  geom_rot <- (sf::st_geometry(x) - center) * rot_matrix + center
  
  sf::st_geometry(x) <- sf::st_sfc(
    geom_rot,
    crs = crs_x
  )
  
  x
}
