# WARNING - Generated by {fusen} from dev/flat_long_term_trends.Rmd: do not edit by hand # nolint: line_length_linter.

#' Title
#' 
#' Description
#' 
#' @param data 
#' @param response_col character, name of the column containing measurements values
#' @param year_col character, name of the column containing years
#' @param group_vars vector of characters, groupin variables
#' @param all_group_combinations logical, TRUE test all combinations of the different variables from group_vars, FALSE test only with the combination of the group_vars given
#' @param k_max 
#' @param min_n 
#' @param min_years 
#'
#' @return
#' 
#' @export
run_gam_by_parameter <- function(data,
                                 response_col = "RESULTAT",
                                 parameter_col = "PARAMETRE_LIBELLE",
                                 year_col = "year",
                                 group_vars = c("estuary", "haline_zone", "season"),
                                 all_group_combinations = FALSE,
                                 k_max = 6,
                                 min_n = 6,
                                 min_years = 6) {
  
  parameter_sym <- sym(parameter_col)
  
  # Vérifications simples
  required_cols <- c(parameter_col, year_col, response_col, group_vars)
  missing_cols <- setdiff(required_cols, names(data))
  
  if (length(missing_cols) > 0) {
    stop(
      "Colonnes absentes du tableau : ",
      paste(missing_cols, collapse = ", ")
    )
  }
  
  # Crée les combinaisons de variables de groupement si demandé
  if (all_group_combinations) {
    
    grouping_list <- map(
      seq_along(group_vars),
      ~ combn(group_vars, .x, simplify = FALSE)
    ) |>
      flatten()
    
  } else {
    
    grouping_list <- list(group_vars)
  }
  
  map_dfr(grouping_list, function(current_group_vars) {
    
    grouping_syms <- syms(c(parameter_col, current_group_vars))
    
    data |>
      group_by(!!!grouping_syms) |>
      nest() |>
      mutate(
        gam_stats = map(
          data,
          ~ safe_gam(
            df = .x,
            response_col = response_col,
            year_col = year_col,
            k_max = k_max,
            min_n = min_n,
            min_years = min_years
          )
        ),
        grouping = paste(current_group_vars, collapse = " + ")
      ) |>
      select(-data) |>
      unnest(gam_stats)
  })
}
