# WARNING - Generated by {fusen} from dev/flat_long_term_trends.Rmd: do not edit by hand # nolint: line_length_linter.

#' Title
#' 
#' p_value < 0.05 : effet significatif de l’année.
#' edf ≈ 1 : tendance quasi linéaire.
#' edf > 1.5–2 : trajectoire non linéaire, donc potentiellement plus intéressante que le simple Mann-Kendall.
#' deviance_explained : part de variabilité expliquée par le modèle.
#' 
#' @param df 
#'
#' @return
#' 
#' @noRd
library(dplyr)
library(tidyr)
library(purrr)
library(mgcv)
library(rlang)
library(tibble)

safe_gam <- function(df,
                     response_col = "RESULTAT",
                     year_col = "year",
                     k_max = 6,
                     min_n = 6,
                     min_years = 6) {
  
  
  response_sym <- sym(response_col)
  year_sym <- sym(year_col)
  
  df_mod <- df |>
    filter(
      !is.na(!!response_sym),
      !is.na(!!year_sym)
    ) |>
    arrange(!!year_sym)
  
  n_obs <- nrow(df_mod)
  n_years <- n_distinct(df_mod[[year_col]])
  
  empty_stats <- tibble(
    n = n_obs,
    n_years = n_years,
    edf = NA_real_,
    F = NA_real_,
    p_value = NA_real_,
    deviance_explained = NA_real_,
    trend_type = "not tested"
  )
  
  empty_predictions <- df_mod |>
    transmute(
      year = .data[[year_col]],
      observed = .data[[response_col]],
      fitted_gam = NA_real_
    )
  
  if (n_obs < min_n || n_years < min_years) {
    return(list(
      stats = empty_stats,
      predictions = empty_predictions
    ))
  }
  
  k_use <- min(k_max, n_years - 1)
  
  if (k_use < 3) {
    return(list(
      stats = empty_stats,
      predictions = empty_predictions
    ))
  }
  
  formula_gam <- as.formula(
    paste0(response_col, " ~ s(", year_col, ", k = ", k_use, ")")
  )
  
  mod <- tryCatch(
    mgcv::gam(
      formula_gam,
      data = df_mod,
      method = "REML"
    ),
    error = function(e) NULL
  )
  
  if (is.null(mod)) {
    failed_stats <- empty_stats |>
      mutate(trend_type = "model failed")
    
    return(list(
      stats = failed_stats,
      predictions = empty_predictions
    ))
  }
  
  sm <- summary(mod)
  
  edf <- sm$s.table[1, "edf"]
  F_value <- sm$s.table[1, "F"]
  p_value <- sm$s.table[1, "p-value"]
  dev_exp <- sm$dev.expl
  
  trend_type <- case_when(
    is.na(p_value) ~ "not tested",
    p_value >= 0.05 ~ "no significant temporal pattern",
    p_value < 0.05 & edf <= 1.5 ~ "linear / monotonic temporal trend",
    p_value < 0.05 & edf > 1.5 ~ "non-linear temporal pattern"
  )
  
  stats <- tibble(
    n = n_obs,
    n_years = n_years,
    edf = edf,
    F = F_value,
    p_value = p_value,
    deviance_explained = dev_exp,
    trend_type = trend_type
  )
  
  predictions <- df_mod |>
    transmute(
      year = .data[[year_col]],
      observed = .data[[response_col]],
      fitted_gam = as.numeric(predict(mod, newdata = df_mod))
    )
  
  gam_results = list(
    stats = stats,
    predictions = predictions
  )

  return(gam_results)
}
