# WARNING - Generated by {fusen} from dev/flat_long_term_trends.Rmd: do not edit by hand # nolint: line_length_linter.

#' Mann-Kendall test p-value
#' 
#' @param x vector
#' 
#' @importFrom modifiedmk mmkh
#'
#' @return function
#' 
#' @noRd
safe_mmkh <- function(x) {
  x <- as.numeric(x)
  x <- x[!is.na(x)]

  if (length(x) < 4) return(NA_real_)

  modifiedmk::mmkh(x)[["new P-value"]]
}
