# WARNING - Generated by {fusen} from dev/flat_long_term_trends.Rmd: do not edit by hand # nolint: line_length_linter.

#' Sen's slope with NAs
#' 
#' @param x vector
#' 
#' @importFrom trend sens.slope
#'
#' @return Sen's slope
#' 
#' @noRd
safe_sen <- function(x) {
  x <- na.omit(x)

  if(length(x) < 2) return(NA_real_)

  as.numeric(trend::sens.slope(x)$estimates)
}
