# WARNING - Generated by {fusen} from dev/flat_long_term_trends.Rmd: do not edit by hand # nolint: line_length_linter.

#' Get Mann-Kendall test p-value and Sen's slope values by estuary, haline_zone and season
#' 
#' @param data tibble with estuary, haline_zone, season, parameter, RESULTAT variables
#' @param parameter character, variable which trend is to be studied
#'
#' @return tibble with estuary, haline_zone, season, mk_parameter_p, sen_parameter_slope 
#' 
#' @noRd
test_monotonic_trend <- function(data, parameter){
    
  filtered_data <- data |>
    filter(PARAMETRE_LIBELLE == {{parameter}}) |> 
    group_by(estuary, haline_zone, year, season) |> 
    summarise(RESULTAT = mean(RESULTAT, na.rm = TRUE), .groups = "drop") |> 
    tidyr::complete(estuary, haline_zone, season, year)
  
  # Mann-Kendall non-monotonic trend test with autocorrelation correction
  mk_parameter_p <- filtered_data |> 
    arrange(estuary, haline_zone, season, year) |>
    group_by(estuary, haline_zone, season) |> 
    summarise(mk_parameter = safe_mmkh(RESULTAT), .groups = "drop")
  
  # Theil–Sen estimator
  sen_parameter_slope <- filtered_data |> 
    arrange(estuary, haline_zone, season, year) |>
    group_by(estuary, haline_zone, season) |> 
    summarise(sen_slope_parameter = safe_sen(RESULTAT), .groups = "drop")
  
  # Join
  monotonic_stats <- full_join(
  mk_parameter_p,
  sen_parameter_slope,
  by = c("estuary", "haline_zone", "season")
)
  
  return(monotonic_stats)
}
