# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand # nolint: line_length_linter.

#' Theme global pour le package avec police Windows sûre
#' @export
theme_esteem <- function(base_size = 11, base_family = "Arial") {
  ggplot2::theme_minimal(base_size = base_size, base_family = base_family)
}
